### ISSUE TITLE
Assistants do not work on Self-Hosted install w/Claude or Cohere endpoints

### ISSUE THREAD

**Issue by gururise** [huggingface/chat-ui#1005]
** Seems like any endpoint type that is not openai does not work with assistants **

Using any model on the Claude or Cohere endpoints on a SELF HOSTED install, the assistant instructions are **basically ignored**.  I have tried adding a chatml template to the chatPromptTemplate to the .env.local, but it made no difference:

**DOES NOT WORK:**
```
  {
    "name": "CohereForAI/c4ai-command-r-plus",
    "id": "command-r-plus",
    "description" : "Command R+ is an instruction-following conversational model that performs language tasks at a higher quality, more reliably, and with a longer context than previous models. It is best suited for complex RAG workflows and multi-step tool use.",
    "preprompt": "",
    "chatPromptTemplate" : "{{#if @root.preprompt}}<|im_start|>system\n{{@root.preprompt}}<|im_end|>\n{{/if}}{{#each messages}}{{#ifUser}}<|im_start|>user\n{{content}}<|im_end|>\n<|im_start|>assistant\n{{/ifUser}}{{#ifAssistant}}{{content}}<|im_end|>\n{{/ifAssistant}}{{/each}}",
    "parameters": {
      "temperature": 0.4,
      "top_p": 0.9,
      "top_k": 50,
      "truncate": 65000,
      "max_new_tokens": 3128,
    },
    "endpoints" : [{
      "type": "cohere"
    }],
  },
```
**DOES NOT WORK:**
```
  {
      "name": "claude-3-sonnet-20240229",
      "displayName": "Claude 3 Sonnet",
      "description": "Ideal balance of intelligence and speed",
      "preprompt": "",
      "chatPromptTemplate" : "{{#if @root.preprompt}}<|im_start|>system\n{{@root.preprompt}}<|im_end|>\n{{/if}}{{#each messages}}{{#ifUser}}<|im_start|>user\n{{content}}<|im_end|>\n<|im_start|>assistant\n{{/ifUser}}{{#ifAssistant}}{{content}}<|im_end|>\n{{/ifAssistant}}{{/each}}",
      "parameters": {
        "temperature": 0.4,
        "top_p": 0.95,
        "top_k": 50,
        "max_new_tokens": 3128,
        "truncate": 65128,
      },
      "endpoints": [
        {
          "type": "anthropic",
          // optionals
          "baseURL": "https://api.anthropic.com",
          defaultHeaders: {},
          defaultQuery: {}
        }
      ]
  },
```
**WORKS:**
```
  {
    "name": "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
    "displayName": "Nous-Hermes-2-Mixtral-DPO",
    "description" : "Nous Hermes 2 Mixtral 8x7B DPO is the new flagship Nous Research model trained over the Mixtral 8x7B MoE LLM.",
    "preprompt": "",
    "chatPromptTemplate" : "{{#if @root.preprompt}}<|im_start|>system\n{{@root.preprompt}}<|im_end|>\n{{/if}}{{#each messages}}{{#ifUser}}<|im_start|>user\n{{content}}<|im_end|>\n<|im_start|>assistant\n{{/ifUser}}{{#ifAssistant}}{{content}}<|im_end|>\n{{/ifAssistant}}{{/each}}",
    "parameters": {
      "temperature": 0.4,
      "top_p": 0.7,
      "top_k": 50,
      "truncate": 30720,
      "max_new_tokens": 2048,
      "stop": ["<|im_end|>","<|im_start|>"]
    },
    "endpoints" : [{
      "type": "openai",
      "baseURL": "https://api.together.xyz/v1",
    }],
  },
```

The assistants work fine on the openai endpoint (tested with gpt-3.5-turbo and Together.ai)

**Comment by nsarrazin** [comment]
Thanks for the report! Could it be that the instructions are not passed correctly? Do you have similar issues if you pass a system prompt directly? (no assistant, just edit the system prompt in settings)

**Comment by gururise** [comment]
System prompt: Act like a pirate.

![Screenshot_20240412_054936_Kiwi Browser](https://github.com/huggingface/chat-ui/assets/4380009/b05d8bbe-87fc-492e-8f8a-cadd11ea98e7)

Seems the custom system prompt is **not** being passed to **claude** or **cohere** models.

**Comment by gururise** [comment]
However if i create a pirate assistant with the same system prompt it does not work: 

![Screenshot_20240412_055931_Kiwi Browser](https://github.com/huggingface/chat-ui/assets/4380009/0b6874ae-57d8-4a9c-be33-83f28ef68931)
![Screenshot_20240412_060315_Kiwi Browser](https://github.com/huggingface/chat-ui/assets/4380009/b15932ef-a6f6-4d56-87d5-7892860eda75)

A few things i noticed:
- the assistant would give me an error about an invalid int for temp and top P & K unless i manually added a temperature, top P and K in the assistant form. 
- even after adding temp, P, K an error message would flash quickly on every response. It was too far for me to capture. But the model still responds, just not using the assistant instructions.

**Comment by nsarrazin** [comment]
Closing with #1023
