### ISSUE TITLE
Frequent errors

### ISSUE THREAD

**Issue by Waingro24** [huggingface/chat-ui#1042]
Frequent errors makes the app almost unusable

![Schermata del 2024-04-21 19-17-53](https://github.com/huggingface/chat-ui/assets/165502201/da367c55-768d-47fb-acf4-62a6b076a018)

**Comment by nsarrazin** [comment]
Hey there was an issue that would occasionally kill one of our replicas and it wouldn't get restarted when that happened. It should be fixed now 😄
