### ISSUE TITLE
[v0.8.2] Assistants not showing up once created

### ISSUE THREAD

**Issue by adhishthite** [huggingface/chat-ui#1066]
Hello!

I am trying to extend HuggingChat for my own use case, however, I have noticed that once an assistant is created, I cannot see it in the "Assistants" page.

## Context

I have created an assistant called `ProPython`. I can see it on the **Models** page AND on the backend.

<img width="1181" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/14d8e9a0-4e4b-4079-95cf-8ccb45adf125">

<img width="690" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/ffbcf959-63ce-43f5-a0ea-f84f2f1f3dac">

## Issue

When I open the **Assistants** page, I don't see anything. I do not see any relevant logs too.

<img width="1390" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/5cf4b872-c5f5-45d0-9bef-be560a4e239f">

<img width="1134" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/311f2edd-9bef-47a4-97b9-4c409b9d62ae">

**Comment by nsarrazin** [comment]
Hi, the issue was fixed in the latest release. I generated a new release `0.8.3` that should fix your issue. Let me know if that works!

**Comment by adhishthite** [comment]
This is fixed! Awesome, thanks so much <3

**Comment by Arche151** [comment]
@nsarrazin Do you have an idea, why the Assistants feature doesn't show up for me at all?

![image](https://github.com/huggingface/chat-ui/assets/124050126/dd667349-b434-4548-ad74-8899266f12fd)

![image](https://github.com/huggingface/chat-ui/assets/124050126/bade543b-7537-41b9-93ed-4334b3cc8406)

I followed the instructions, set up the .env.local and ran the server with npm run dev but I can't find the Assistants feature anywhere :(
