### ISSUE TITLE
[v0.8.3] serper, serpstack API, local web search not working

### ISSUE THREAD

**Issue by adhishthite** [huggingface/chat-ui#1072]
## Context

I have serper.dev API key, serpstack API key and I have put it correctly in my `.env.local` file.

<img width="478" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/5082893a-7ecd-4ab5-9cb9-059875118dcd">

## Issue

However, even if I enable Web Search, it still does not reach out to those APIs, and shows me "an error occured" no the Web Search part.

<img width="931" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/da96c121-89e0-402b-8e93-33c9e6709c71">

I don't see calls reaching Serper and SerpStack as well.

<img width="1365" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/7230b1a0-2567-424f-8884-8fc53417fa41">

<img width="1302" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/b35c1a7f-1c2c-4c8a-9c46-5c2171f73f9b">

It was working for a bit on `v0.8.2`, but then it stopped working there as well. Now, for `v.0.8.3`, it's not working at all. Am I missing something? I have tried using either of those APIs too, but it still does not work.

Please help.

**Comment by nsarrazin** [comment]
Oh `USE_LOCAL_WEBSEARCH` will attempt to search the web by fetching google search directly and parsing the resulting page.  It will override other websearch APIs. It's a bit more unstable than using an API, try removing this flag and let me know if that works. 

Also we don't support using multiple search queries at the same time so if you set both serpapi and serper, the priority will be given to serper with our current setup.

**Comment by adhishthite** [comment]
@nsarrazin 

Thanks! I disabled the local web search and kept only Serper.

I see, but here's what's happening now. Even though Serper received the query, the UI shows an error.

<img width="936" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/e8592cff-1b9a-42b9-b479-1fdfa5938bba">

<img width="1273" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/4e8f57c1-bbf3-437b-bd80-c594b1ffa71e">

Is there something I am missing?

**Comment by adhishthite** [comment]
@nsarrazin  here you go

<img width="761" alt="image" src="https://github.com/huggingface/chat-ui/assets/31769894/d1b59da9-fcd1-4213-a85a-743cad658256">

**Comment by nsarrazin** [comment]
Do you have a custom `TEXT_EMBEDDING_MODELS` maybe ?

**Comment by adhishthite** [comment]
@nsarrazin Yes, I have this custom embedding:

```
TEXT_EMBEDDING_MODELS=`[
    {
        "name":"azure-openai-text-embedding-3-large",
        "displayName":"Azure OpenAI Text Embedding 3 Large",
        "description":"Azure OpenAI Text Embedding 3 Large model hosted on Azure. This model is capable of generating embeddings for text data and can be used for a variety of tasks such as semantic search, clustering, and more.",
        "chunkCharLength":8191,
        "endpoints":[
            {
                "type":"openai",
                "baseURL":"https://MYDEP-dev.openai.azure.com/openai/deployments/itgpt-text-embedding-3-large",
                "defaultHeaders":{
                    "api-key":"xxxx"
                },
                "defaultQuery":{
                    "api-version":"2024-02-01"
                }
            }
        ]
    }
]`
```

**Comment by adhishthite** [comment]
@nsarrazin Is there a way to check if the custom text embedding model is set up correctly? So that this error can be caught before.

**Comment by nsarrazin** [comment]
It's kind of hard to test right now, you should probably add a bunch of logs in `src/lib/server/embeddingEndpoints/openai/embeddingEndpoints.ts` . I haven't really used the `openai` embeddings yet so it could be just broken, I'll investigate. 

In the meantime the default embedding shouldn't require any external API and just runs on the CPU, if that helps 😅

**Comment by adhishthite** [comment]
@nsarrazin This is working! I think I will have to re-check the OpenAI embeddings. I will have around 1000+ users once I deploy, so an API based embedding approach was desirable.

**Comment by nsarrazin** [comment]
For sure!

You can also deploy [text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference), either self-hosted or using an [Inference Endpoint](https://ui.endpoints.huggingface.co/). This is what we use for HuggingChat [(config)](https://github.com/huggingface/chat-ui/blob/3d83131e5d03e8942f9978bf595a7caca5e2b3cd/.env.template#L255-L266) and it handles the load pretty well.

But we of course have a goal of supporting a wide variety of endpoints so i'll try to see what the issue is with the OpenAI endpoint type. 🤔

**Comment by adhishthite** [comment]
Thanks so much! @nsarrazin Closing this issue, but please try to fix the OpenAI issue. I am taking a look at it myself too.

**Comment by adhishthite** [comment]
@nsarrazin Please take a look: https://github.com/huggingface/chat-ui/pull/1077
