### ISSUE TITLE
I want to get the html of a website https://bit.ly/4bgmLb9 in huggingchat web search

### ISSUE THREAD

**Issue by fancy45daddy** [huggingface/chat-ui#1093]
I want to get the html of a website https://bit.ly/4bgmLb9 in hugging-chat web search. In chrome, I can put https://bit.ly/4bgmLb9 in the address bar and get the result. But I do not know how to do that in hugging-chat web search?

I try in hugging-chat and the screenshot 
![tmp](https://github.com/huggingface/chat-ui/assets/124528204/89ca5f28-9dc9-479c-a6f0-9c096e8ea0d6)

how to write the prompt so that huggingchat can fullfill the requirement

**Comment by nsarrazin** [comment]
Best option would be to make an assistant, make sure dynamic prompt is enabled and add `{{url:http://your-url-here.com}}` inside of the system instructions. That should work.
