### ISSUE TITLE
Web search option is not working properly.

### ISSUE THREAD

**Issue by siddhantdante** [huggingface/chat-ui#1166]
![image](https://github.com/huggingface/chat-ui/assets/44642083/ae3a6174-866a-4827-87dd-a0750bc961a9)

**Comment by YWaller** [comment]
I also have this issue. These URLs worked yesterday, they do not work today. One url is a github.io the other is an aws link, so it's not github or amazon's fault.


Using links specified in Assistant
Browsing search results
Failed to parse webpage
browserContext.newPage: Target page, context or browser has been closed,[link removed for clarity]

Failed to parse webpage
browserContext.newPage: Target page, context or browser has been closed,[link removed for clarity]

An error occurred

**Comment by YWaller** [comment]
I've been investigating a bit. This feature was working yesterday, but today it's broken.
If you go here:
https://github.com/huggingface/chat-ui/tree/main/src/lib/server/websearch

You'll see that an update was pushed yesterday. I don't find this to be a coincidence. I don't know much about playwright or anything, but from my search it seems the error is probably in one of these files:
https://github.com/huggingface/chat-ui/blame/102ff2d374d699d7a2e6163ca95adbe486ed1c30/src/lib/server/websearch/update.ts

https://github.com/huggingface/chat-ui/blob/102ff2d374d699d7a2e6163ca95adbe486ed1c30/src/lib/server/websearch/runWebSearch.ts

https://github.com/huggingface/chat-ui/blob/102ff2d374d699d7a2e6163ca95adbe486ed1c30/src/lib/server/websearch/search/search.ts

https://github.com/huggingface/chat-ui/blame/102ff2d374d699d7a2e6163ca95adbe486ed1c30/src/lib/server/websearch/scrape/playwright.ts

https://github.com/huggingface/chat-ui/blame/102ff2d374d699d7a2e6163ca95adbe486ed1c30/src/lib/server/websearch/scrape/scrape.ts

I'll keep digging, but I don't have the know-how to fix this, really. But hopefully narrowing it down to yesterday's update and these files helps whoever actually can.

**Comment by starlord263** [comment]
I am facing same on hugging chat online version.

**Comment by Saghen** [comment]
Fixed in #1171
