### ISSUE TITLE
Inconsistency in docs: HF_TOKEN vs HUGGING_FACE_HUB_TOKEN

### ISSUE THREAD

**Issue by rodrigobdz** [huggingface/chat-ui#1185]
When following the docs on Chat UI, the readme mentions `HF_TOKEN` should be set. The tutorial linked from the readme mentions `HUGGING_FACE_HUB_TOKEN` should be set instead.

Inspecting the code reveals that `HF_TOKEN` is used for Chat UI. Should `HUGGING_FACE_HUB_TOKEN` be removed from the [Chat UI docs](https://github.com/huggingface/hub-docs/blob/74868a57b706d56e6735af4345cd64f32c30fd2a/docs/hub/spaces-sdks-docker-chatui.md#L16)?

## Docs

https://github.com/huggingface/chat-ui/blob/309f2269d4dd0922ee9e49c0e636acbcf825cb70/README.md#L37

https://github.com/huggingface/hub-docs/blob/74868a57b706d56e6735af4345cd64f32c30fd2a/docs/hub/spaces-sdks-docker-chatui.md#L16

**Comment by julien-c** [comment]
yes! can you update it there?
