### ISSUE TITLE
Allow users to delete chat entries.

### ISSUE THREAD

**Issue by Prezombie** [huggingface/chat-ui#1210]
It's rather annoying how there's no way to delete single chat entries, only edit your own or regenerate the AI response. Especially considering loading an old chat involves fiddling with every node that was edited or regenerated to get to the current position.

**Comment by nsarrazin** [comment]
Hi, I think that makes sense, if someone feels like tackling it feel free! Otherwise I might take a look when I have time

**Comment by omesh-omg** [comment]
hello @nsarrazin  and @Prezombie  can I work on this

**Comment by nsarrazin** [comment]
Sure thing! Would be a nice feature to see. 

How about showing a trash icon if a message has more than 1 children ? ![Screenshot from 2024-06-01 06-49-37](https://github.com/huggingface/chat-ui/assets/25119303/4a54c271-62a8-4261-83c0-04752c10e29f)

Then you would need a `deleteBranch` form action in `src/routes/conversation/[id]/+page.server.ts` which sends the message ID in the form

The delete should delete every message that contain the message ID in their `ancestors` property, as well as the message itself. That should do the trick! Let me know if you need more details

**Comment by omesh-omg** [comment]
just built the project locally and went through the code do we have a icon library to use for the delete icon or should I use some random icon there?

**Comment by nsarrazin** [comment]
I think you can use the [trashcan icon we use for deleting conversations](https://github.com/huggingface/chat-ui/blob/93b39a0beb72378c76d5d146bfd3a8355c1d110d/src/lib/components/NavConversationItem.svelte#L7-L8)

**Comment by krakenftw** [comment]
I have added the basic things needed and created the action, my question is how do i send the `Message.id` form page to `deleteBranch`. stuck here : /

**Comment by nsarrazin** [comment]
> I have added the basic things needed and created the action, my question is how do i send the `Message.id` form page to `deleteBranch`. stuck here : /

You could wrap the button in a [form](https://kit.svelte.dev/docs/form-actions#default-actions) with an input `type='hidden'` with name `messageId` and value `message.id` to send the data to the form.

Feel free to open a draft PR and I can help review there 😄

**Comment by krakenftw** [comment]
@nsarrazin  can you have a look please?
https://github.com/huggingface/chat-ui/pull/1237

**Comment by krakenftw** [comment]
wanted a bit of clarification on this, does `deleteBranch` delete the whole message including the regenerated ones?

**Comment by nsarrazin** [comment]
Just the current branch, so if you're on 1/12 for example, afterwards there should only be 11 branches left.

But it should delete any message that comes after the one you're deleting in the DB (since they can't be shown anyway, that's why you filter on the `ancestors` property). And the option shouldn't be visible if you only have one branch. (only show if you see the < 1/2 > indicator)

**Comment by krakenftw** [comment]
can you have a look at this once? @nsarrazin 
https://github.com/huggingface/chat-ui/compare/main...krakenftw:chat-ui:fix%231210?expand=1

**Comment by omesh-omg** [comment]
okay @krakenftw  you can work on this

**Comment by krakenftw** [comment]
@nsarrazin Is there a bug with branching? Whenever i try to regenerate a message, it disappears all the messages below it. Makes them connected to the branch i've changed
<img width="821" alt="image" src="https://github.com/huggingface/chat-ui/assets/64185252/5ff397a7-ff08-4325-8836-72fd1f4c3c09">
<img width="877" alt="image" src="https://github.com/huggingface/chat-ui/assets/64185252/ee73c43f-0860-4f02-94bf-1c6f4839d491">
Like this
