### ISSUE TITLE
A few questions about the Cloudflare integration

### ISSUE THREAD

**Issue by kodster28** [huggingface/chat-ui#1220]
Howdy 👋 ,

Working on a corresponding page for this in the [Cloudflare docs](https://developers.cloudflare.com/workers-ai/) and had a few [questions that I need answered](https://github.com/cloudflare/cloudflare-docs/pull/14488#issuecomment-2101481990) in this PR.

## Questions

1. If I'm reading [this line](https://github.com/huggingface/chat-ui/blob/25d6df858f15128e6ca23214ce7ad08f176a68ed/src/lib/server/endpoints/cloudflare/endpointCloudflare.ts#L18C21-L18C29) correctly, it sounds like [their example is actually incorrect](https://github.com/huggingface/chat-ui/blob/main/README.md?plain=1#L598) and might need to be updated?
2. If ^^^ is correct, does that mean that we should also be specifying the [`model` parameter](https://github.com/huggingface/chat-ui/blob/25d6df858f15128e6ca23214ce7ad08f176a68ed/src/lib/server/endpoints/cloudflare/endpointCloudflare.ts#L19) w/in the endpoint configuration?
3. Correct assumption that this only works with models prefixed with `@hf`, think so based on [their code](https://github.com/huggingface/chat-ui/blob/25d6df858f15128e6ca23214ce7ad08f176a68ed/src/lib/server/endpoints/cloudflare/endpointCloudflare.ts#L19).

Mind helping me out so I can get this live in our docs?

**Comment by nsarrazin** [comment]
Hey! Thanks for taking a look at this.

1. Yes our example is incorrect, will update the docs to fix it
2. No need, `model` is passed from inside chat-ui so it's all good.
3. Yes I think so for now, though it could be made configurable if we want! (and if the APIs are compatible, not sure how it works cloudflare side)

**Comment by kodster28** [comment]
> Hey! Thanks for taking a look at this.
> 
> 1. Yes our example is incorrect, will update the docs to fix it
> 2. No need, `model` is passed from inside chat-ui so it's all good.
> 3. Yes I think so for now, though it could be made configurable if we want! (and if the APIs are compatible, not sure how it works cloudflare side)

Thanks @nsarrazin, happy to close out this issue or let you do it as this has answered my questions. I'll bring up 3 with the PM.

**Comment by kodster28** [comment]
Related #1226
