### ISSUE TITLE
Add confirmation mechanism when deleting a branch

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#1262]
See [hub issue](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/479) 

With the release of the "delete branch" feature, it's possible to one click delete a large chunk of a conversation. We should have some kind of confirmation mechanism before deleting a branch, probably the same one that we have when deleting a conversation in the sidebar, or a modal.

**Comment by manaskhandelwal** [comment]
@nsarrazin Can you assign this to me?
