### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by renaldy-therry** [huggingface/chat-ui#1270]
Hi, I am chatting with different models (mixtral, llama3, c4ai, etc ) in huggingchat website (https://huggingface.co/chat/) but i got error "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by renaldy-therry** [comment]
![huggingchat error](https://github.com/huggingface/chat-ui/assets/86903328/78946d91-7e9f-4b1e-accb-25c8f1662330)

**Comment by AlaouiMdaghriAhmed** [comment]
same every action end up with the same error : 
![image](https://github.com/huggingface/chat-ui/assets/77700915/1476868d-6672-475e-8488-0809efa06431)

**Comment by nsarrazin** [comment]
On it! Noticed the issue as well.

**Comment by nsarrazin** [comment]
Should be resolved
