### ISSUE TITLE
Misspelt envvar: "LLM_SUMMERIZATION"

### ISSUE THREAD

**Issue by marksverdhei** [huggingface/chat-ui#1289]
https://github.com/huggingface/chat-ui/blob/fc5262974a556bf308943770a961b7ccbf8dcb4e/.env#L140  
https://github.com/huggingface/chat-ui/blob/fc5262974a556bf308943770a961b7ccbf8dcb4e/src/lib/server/textGeneration/title.ts#L29
Should be `LLM_SUMMARIZATION`

**Comment by nsarrazin** [comment]
Ha nice, thanks for the catch, if someone wants to tackle feel free
