### ISSUE TITLE
Option to turn on/off playwright (adblocker).

### ISSUE THREAD

**Issue by calycekr** [huggingface/chat-ui#1298]
There are many problems due to playwright in offline environment. I have to wait for playwright fetch timeout before the application is fully loaded.

`ERROR (1399872): Failed to initialize PlaywrightBlocker from prebuilt lists`

I need an option to turn it on and off.
Please add an option to turn it off, not to deal with errors.

**Comment by nsarrazin** [comment]
Makes a lot of sense to me! Let me know if someone wants to tackle this, I think putting an env variable `PLAYWRIGHT_ADBLOCK=true` by default in the `.env` which could be set to `false` should work.

**Comment by krakenftw** [comment]
can i work on this? @nsarrazin

**Comment by nsarrazin** [comment]
Sure thing @krakenftw

**Comment by nsarrazin** [comment]
Just using an env variable in `.env` yes

**Comment by krakenftw** [comment]
@calycekr Yeah, i did add a  boolean env, and disabling `blocker` based on that env. It has'nt been merged yet tho.
Hoping a response from @nsarrazin

**Comment by nsarrazin** [comment]
thanks for noticing @calycekr should be fixed with https://github.com/huggingface/chat-ui/commit/df67a2c0ba5140d68241589e1f73da03cc3c3843 ! let me know if not
