### ISSUE TITLE
"Sign in with 🤗 Hugging Face" button for login modal can look strange at narrow widths

### ISSUE THREAD

**Issue by Mardak** [huggingface/chat-ui#1314]
Relatively minor issue with left side of this screenshot shows the beginning and end of the button text overflowing:
<img width="1198" alt="narrow hugging chat login" src="https://github.com/huggingface/chat-ui/assets/438537/67f79795-c932-471d-9667-f0b0c57f0629">

The current code happens to have newline/whitespace that could be preserved or somehow shorten the text?
https://github.com/huggingface/chat-ui/blob/70e1e30dc333e0506b07e3a1477f3c706e8f6080/src/lib/components/LoginModal.svelte#L38-L44

**Comment by julien-c** [comment]
good catch, a PR is welcome!

**Comment by Mardak** [comment]
Specifically for the Firefox chatbot sidebar use case, we might end up enforcing a minimum width of say 420px and avoid this issue for huggingchat that only appears around 350px.
