### ISSUE TITLE
Adding husky to the project so it lints pre-commit

### ISSUE THREAD

**Issue by krakenftw** [huggingface/chat-ui#1317]
Adding husky to the project would help with lint stuff, it can lints pre commit.

**Comment by krakenftw** [comment]
I've a branch with husky already added. If its a good enhancement, let me know i will submit a PR.

**Comment by nsarrazin** [comment]
Feel free to submit a PR if you already have a branch, not super familiar with Husky but it looks nice and could help contributors I guess 😄
