### ISSUE TITLE
Command-R-plus model parameters

### ISSUE THREAD

**Issue by li-ruijie** [huggingface/chat-ui#1329]
I have tried to replicate the behaviour of Command-R-plus locally with TGI and chat-ui but could not get anywhere near the length of answer that huggingchat provides. May I know the parameters used for serving the command-r and command-r-plus models?

**Comment by nsarrazin** [comment]
Hi! Yes our config is fully open-source, you can find the details here: https://github.com/huggingface/chat-ui/blob/b5a0f56b00d3feaf663b576857005abdad149fe1/chart/env/prod.yaml#L41-L67
