### ISSUE TITLE
huggingchat is down

### ISSUE THREAD

**Issue by renaldy-therry** [huggingface/chat-ui#1334]
![image](https://github.com/huggingface/chat-ui/assets/86903328/a13160ca-cb11-41b5-9565-2fb920a6f4f3)

**Comment by gabrielparca** [comment]
back up for a bit... all conversations wiped out.. went dark again

**Comment by nsarrazin** [comment]
Hi, we're aware of it and working on it 😄

**Comment by gabrielparca** [comment]
thank you for your zeal 🫡

**Comment by nsarrazin** [comment]
Should be back up!
