### ISSUE TITLE
Bug: PUBLIC_APP_DISCLAIMER=0 still shows disclaimer dialog

### ISSUE THREAD

**Issue by rodrigobdz** [huggingface/chat-ui#1359]
I expect `.env.local` to override `.env`, but it seems to be the other way around.

https://github.com/huggingface/chat-ui/blob/7d3eb761d4dbca791fb2fdb13d55894ac8c3cf82/svelte.config.js#L5-L6

I noticed this when trying without success to skip the disclaimer with the following line in `.env.local` since [`.env`](https://github.com/huggingface/chat-ui/blob/7d3eb761d4dbca791fb2fdb13d55894ac8c3cf82/.env#L134-L140) sets the `PUBLIC_` variables by default.

```
PUBLIC_APP_DISCLAIMER=0
```

**Comment by rodrigobdz** [comment]
I can submit a PR with the following change to make `.env.local` override `.env`:

```diff
+ dotenv.config({ path: "./.env" }); 
dotenv.config({ path: "./.env.local" }); 
- dotenv.config({ path: "./.env" }); 
```

**Comment by rodrigobdz** [comment]
I also tried setting the `PUBLIC_APP_DISCLAIMER` variable to `0` in `.env` as follows but that also didn't work (the disclaimer dialog is still showing.

```
PUBLIC_APP_DISCLAIMER=0
```

**Comment by rodrigobdz** [comment]
However, changing the `PUBLIC_APP_NAME` in `.env` works—i.e., change is reflected on the website.

**Comment by rodrigobdz** [comment]
The issue is that `PUBLIC_APP_DISCLAIMER` is not taken into account in the logic to display the disclaimer modal.

https://github.com/huggingface/chat-ui/blob/7d3eb761d4dbca791fb2fdb13d55894ac8c3cf82/src/routes/%2Blayout.svelte#L185-L187

**Comment by nsarrazin** [comment]
Oh thanks for catching that! Looks like we were not using the env variable correctly at all :melting_face:  Opened #1360 to fix this, will merge let me know if that solves your issue

**Comment by rodrigobdz** [comment]
@nsarrazin Thanks for the swift response. Could we reopen this issue?

While the disclaimer is gone, I cannot use the Chat UI website because the following errors are shown in the browser console when trying to start a chat:

```
Error while creating conversation: {"error":"You need to accept the welcome modal first"}
```

```
Error while creating conversation: "Oops, something went wrong."
```

The settings expect the key `ethicsModalAccepted` to be set before starting a conversation.

https://github.com/huggingface/chat-ui/blob/7692f71091e027a99195d6bcff6a2ec8c9180983/src/routes/%2Blayout.server.ts#L140

**Comment by nsarrazin** [comment]
Could you try the latest main and tell me what your `PUBLIC_APP_DISCLAIMER` is set to? With the latest changes I couldn't reproduce the issue

**Comment by rodrigobdz** [comment]
It is set to `0` as follows in the `.env` file: 

```
PUBLIC_APP_DISCLAIMER=0
```

I will try the latest `main`.

**Comment by rodrigobdz** [comment]
Given the disclaimer in `.env` about changes to the file (pasted below), the changes outlined in https://github.com/huggingface/chat-ui/issues/1359#issuecomment-2248352144 will be necessary to give `.env.local` precedence over `.env` — i.e., to allow `.env.local` to override values in `.env`. 

```
# Use .env.local to change these variables
# DO NOT EDIT THIS FILE WITH SENSITIVE DATA
```

**Comment by nsarrazin** [comment]
But it's already the case no ? `dotenv.config` has `override: false` by default so you should put the highest priority config first

Try setting `PUBLIC_APP_NAME` in both the `.env` and `.env.local` and see which one is used for example.

Is the issue with the disclaimer still happening ?

**Comment by rodrigobdz** [comment]
Ah, sorry! It's seems like a XY problem. I'll forget about the dotenv files for now and focus back on the actual issue with `PUBLIC_APP_DISCLAIMER`. 

My CI is redeploying the Chat UI and will report in a few minutes the results.

**Comment by rodrigobdz** [comment]
Issue has been solved now. Thanks for the quick response, Nathan!
