### ISSUE TITLE
Cannot send the message and get response in hugging chat

### ISSUE THREAD

**Issue by renaldy-therry** [huggingface/chat-ui#1392]
I cannot send message and get a response from llm, and i cannot click "activate" to change model in huggingchat (https://huggingface.co/chat/)

**Comment by nsarrazin** [comment]
Can you tell me which browser/OS are you using ?

**Comment by renaldy-therry** [comment]
I am using mozilla firefox new version and windows 11 
I am trying in brave and huggingchat can work

**Comment by nsarrazin** [comment]
I'm also using Firefox and don't have any issues :sweat_smile: Could you make sure this is not an issue with a browser extension or some browser setting ?

**Comment by renaldy-therry** [comment]
yeah , i will close it, i think  there is something wrong with my browser
