### ISSUE TITLE
I need to reload to get the response

### ISSUE THREAD

**Issue by renaldy-therry** [huggingface/chat-ui#1394]
![image](https://github.com/user-attachments/assets/7f7ec4b0-7978-468e-b793-d460d528ba84)
i am using LLama 3.1 70B to chat, but it is so slow to get response and i need to reload to get response , is it because the model is overload ?

**Comment by nsarrazin** [comment]
Is this on huggingchat or a self hosted version of chat-ui ? What browser/OS combination are you using? Is it still happening now ?

**Comment by nsarrazin** [comment]
closing for now, will reopen if you want when you get back to me 😄
