### ISSUE TITLE
Cannot change environment variables

### ISSUE THREAD

**Issue by Winvoker** [huggingface/chat-ui#1410]
### Bug description

The environment variable is poorly formatted due to containing whitespaces and incorrect JSON syntax. This is causing issues when trying to run the Docker container.

### Steps to reproduce

1. Create an environment file (`.env.local`) with the variable:
   ```plaintext
   MODELS=`[
     {
       "name": "HuggingFaceM4/idefics-80b-instruct",
       "multimodal" : true,
       "description": "IDEFICS is the new multimodal model by Hugging Face.",
       "preprompt": "",
       "chatPromptTemplate" : "{{#each messages}}{{#ifUser}}User: {{content}}{{/ifUser}}<end_of_utterance>\nAssistant: {{#ifAssistant}}{{content}}\n{{/ifAssistant}}{{/each}}",
       "parameters": {
         "temperature": 0.1,
         "top_p": 0.95,
         "repetition_penalty": 1.2,
         "top_k": 12,
         "truncate": 1000,
         "max_new_tokens": 1024,
         "stop": ["<end_of_utterance>", "User:", "\nUser:"]
       }
     }
   ]`
2. Run the docker container
```
docker run -p 3000:3000 --env-file .env.local -v chat-ui:/data --name chat-ui ghcr.io/huggingface/chat-ui-db
```

3. Logs
```
docker: poorly formatted environment: variable '"name": "HuggingFaceM4/idefics-80b-instruct",' contains whitespaces.
```

OS : Ubuntu

**Comment by nsarrazin** [comment]
Docker env files require different formatting than the one we use with node. 

We support a `DOTENV_LOCAL` var if you want to just pass the whole thing as a var:

```
DOTENV_LOCAL=$(<.env.local)  docker run -e DOTENV_LOCAL -p 3000:3000 chat-ui
```

or you can use a bind volume
```
docker run --mount type=bind,source="$(pwd)/.env.local",target=/app/.env.local -p 3000:3000 chat-ui
```

**Comment by nsarrazin** [comment]
(you can also just specify each var individually if that's easier, depending on your setup)

**Comment by Winvoker** [comment]
Now chat-ui works however it does not recognize my environment variables. Only mistral-7b default model is used and my HF_TOKEN is not recognized as well.
