### ISSUE TITLE
Add a model config option to disable system prompts

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#1432]
## Describe your feature request

Some models don't support system prompts and if you try to use the `system` role in their chat template they throw an error. We should add a config option in the model definition to specify that system prompts are not supported. In that case we 

## Implementation idea

add a `systemPrompt: true|false` in the `modelConfig` which will trigger logic to filter out `role: 'system'` messages and preprend the content of the first one to the first user message

Solves #1386

**Comment by Mounayer** [comment]
Hi there, I could give this a try!
