### ISSUE TITLE
Bug in Search Use in tool capable models.

### ISSUE THREAD

**Issue by KingNish24** [huggingface/chat-ui#1443]
I found a bug that if Assistant is using any of the tools calling model Llama 70b and Command r+. It uses web search for some queries even when web search of assistant set to Default (which specified as off ). 

Example Chat:
https://hf.co/chat/r/ZtDaniu

**Comment by pearsonkyle** [comment]
Finding the same issue using Command r+. This behavior degrades the overall quality of the output by fluffing the context with irrelevant information and increases the response time thus contributing to a worse user experience.

**Comment by nsarrazin** [comment]
Thanks for the report! This was fixed with #1452
