### ISSUE TITLE
Scrollbar is not pressable at the right edge of the viewport

### ISSUE THREAD

**Issue by rotemdan** [huggingface/chat-ui#1492]
## Bug description

When the the mouse is located at the right edge of the viewport, the scroll bar is not responsive to clicks (pressing the left mouse button would cause text selection instead, which is not expected behavior).

It requires slight positioning to the left to get it pressed.

This is an issue with many different websites, but I've found a simple way to solve it here.

## Steps to reproduce

1. Position the mouse at the right edge of the viewport
2. Try to press and drag the scrollbar

## Screen capture

![scrollbar-press-at-right-edge](https://github.com/user-attachments/assets/a4bebd6d-86d4-45f7-93fc-77e85965bcdb)

### Specs

- **OS**: Windows 11
- **Browser**: Brave Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)
- **chat-ui commit**: `v0.9.2` (web)

### Temporary fix using a custom stylesheet

1. Install the [Stylus extension](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)

2. Apply this stylesheet to https://huggingface.co/chat/

```css
@-moz-document url-prefix("https://huggingface.co/chat/") {
    div.scrollbar-custom {
        margin-right: 0px !important;
    }
}
```

The stylesheet simply zeros the right margin for the element that includes the scrollbar. The margin is otherwise `4px`, which causes the problem.

### Screen capture after applying stylesheet

![scrollbar-press-at-right-edge-after-custom-stylesheet](https://github.com/user-attachments/assets/9d4e99d5-e3b7-4dae-a60e-e9dc1a93b3d9)

### Thanks

I've been frustrated by this issue for a while now. I'm glad I've found a temporary workaround. 

I would appreciate the issue being fixed for all users. Sometimes what looks like a minor UI fix can make a surprisingly large improvement in the overall user experience.

**Comment by nsarrazin** [comment]
Hi, thanks for reporting an issue! Looks like you already have a fix, if you want to open it as a PR i'll happily review it :rocket:

**Comment by rotemdan** [comment]
The workaround I gave basically overrides some CSS properties with a browser extension.

In order to fix this properly, it should modify the cause of why the margin is added in the first place.

The particular HTML class that adds the margin seems to be `.mr-1`:

![Screenshot_10](https://github.com/user-attachments/assets/155e267f-c9a4-49e6-b3ad-7d60510cec1b)

It's added to the element:

![Screenshot_11](https://github.com/user-attachments/assets/36fe1524-d095-4464-97a0-5ef4e795615a)

There are 4 source file that include a `div` element with the combination of `scrollbar-custom mr-1`:

`src\lib\components\chat\ChatWindow.svelte`
`src\routes\assistants\+page.svelte`
`src\routes\models\+page.svelte`
`src\routes\tools\+page.svelte`

I could just remove `mr-1` from all of them but I'm not really familiar with each does, and not sure how exactly they would be impacted by this.

I can't really make a pull request without being sure what I'm doing makes sense.

**Comment by rotemdan** [comment]
I can see the fix has been applied to the web interface at https://huggingface.co/chat. Thanks.

**Comment by nsarrazin** [comment]
Hi, I'll take a look :smile:

**Comment by nsarrazin** [comment]
pushed a fix for it, deploying now, should be live in 5-10min. thanks for the report!

**Comment by rotemdan** [comment]
The pull request I made was actually to [remove the `mr-1` class from multiple locations](https://github.com/huggingface/chat-ui/pull/1498/commits/a7c6ff9d2de86fbb9d1ccc281f9f8509adaee2a6).

`mr-1`, I believe, means, a right margin of 1. By removing the right margin, the scrollbar became responsive. The recent change made was to add `mr-1`. I don't think that would have the right effect (that would be surprising, in any case).

In the new code I see `mr-1` and `mr-1.5` in many places. I don't know which of them impacts the margin next to a scrollbar. In other words, I don't know which to remove:

![Screenshot_1](https://github.com/user-attachments/assets/b9dd19e2-ebf0-49ae-a878-b0df4279939b)

**Comment by rotemdan** [comment]
The change adds a margin of 4, increasing the gap to the right edge of the viewport:

![Screenshot_2](https://github.com/user-attachments/assets/b37f522d-dd1b-4a56-91d5-ada935f9e7fd)

![Screenshot_3](https://github.com/user-attachments/assets/90c82172-026c-4ba6-8197-f5a5dc9a56e6)

The 4 pixel margin didn't exist before I reloaded the page. So even without a margin on the outer element, the scrollbar wasn't seen by the browser as being positioned at the right edge of the viewport.

Maybe the issue is now related to a margin added to an inner element, not necessarily the outer one. Browsers (testing on Chromium) can be sensitive to these margins, even to fractional pixels sometimes.

**Comment by rotemdan** [comment]
Here is how the Chromium bug looks like, on different zoom levels (website is `open-webui`, not `chat-ui`). In the case of `open-webui`, it occurs at a 110% zoom level, but not on other zoom levels:

![Animation7](https://github.com/user-attachments/assets/f77bc9a1-b556-4865-ae48-b802381200bc)

The chromium bug doesn't occur on all websites, for example, it doesn't happen on Mistral or ChatGPT. I can't quite isolate what minimal circumstances it takes to reproduce it, which makes it hard to submit a good issue on the Chromium tracker.
