### ISSUE TITLE
(BUG) Oath login splash is BROKEN/does NOT work

### ISSUE THREAD

**Issue by bpawnzZ** [huggingface/chat-ui#1509]
On newer versions of chat-ui the login splash screen does not work.  Say for instance you have oauth setup and are not logged in.  You should get a popup prompting you to logina nd not see the interface.  This used to work without a problem.  I just realized this no longer working on the newer versions.  I have oauth set up through huggingface working perfectly. 

Note.. even though the splash is not shown someone would be prevented from using the chatbot as it just wont work if your not logged in. However i kinda like the splash..  Anyone know how to get this working again??  already messed with it? save me some time.  thank you huggingface for creating this project.  Are we going to be getting any of the newer options being implemented into Huggingchat like specifically the continue button and new search/agent control popup panel vs just search on/off??  Thanks and wish yall the best

***Splash on 0.8.4 (Working)
![image](https://github.com/user-attachments/assets/7ada285f-9ff4-4700-8342-e985d14b2d12)

***Splash on 0.9.3 (Not Working)
![image](https://github.com/user-attachments/assets/613fab7e-aff5-4225-9b65-ad073fff49a1)

**Comment by nsarrazin** [comment]
Thanks for the report! Could you share your environment config without secrets ? Would like to try to reproduce this

**Comment by nsarrazin** [comment]
Hi, the issue should be fix with the latest image. Let me know if that's not the case and I'll reopen!
