### ISSUE TITLE
Improve delete conversation UX by swapping confirmation button positions

### ISSUE THREAD

**Issue by flash1729** [huggingface/chat-ui#1546]
## Describe your feature request
Currently, when deleting a conversation, after clicking the delete (trash) icon, the confirm (checkmark) and cancel (cross) buttons appear in a position that requires moving the cursor away from the original click position to confirm deletion. This creates unnecessary mouse movement and reduces the user experience.

The proposal is to swap the positions of the confirm and cancel buttons so that the confirm button appears closer to where the delete icon was, making the deletion process more fluid and intuitive.

## Screenshots (if relevant)
Before:
[Current behavior: Delete icon -> [Cross] [Checkmark]]
![image](https://github.com/user-attachments/assets/a5f4f2a5-cfe9-4064-947f-d24b487d7e86)

![image](https://github.com/user-attachments/assets/23d7820d-d48a-43e9-ad1a-ca1417a3cccd)

## Implementation idea
The change requires modifying the `NavConversationItem.svelte` file to swap the order of the confirm and cancel buttons in the confirmation UI. The modification is simple and doesn't affect any underlying functionality.

I would like to implement this improvement myself. I've already identified the relevant code in `src/lib/components/NavConversationItem.svelte`.

Note: The current shift+click shortcut to bypass confirmation will be maintained.

**Comment by nsarrazin** [comment]
Feel free to tackle this @flash1729! Thanks for tracking the issue

**Comment by flash1729** [comment]
@nsarrazin I have applied the fix, please do review.
