### ISSUE TITLE
Is there any place that uses this environment variable?

### ISSUE THREAD

**Issue by calycekr** [huggingface/chat-ui#1565]
https://github.com/huggingface/chat-ui/blob/ab349d0634ec4cf68a781fd7afc5e7fdd6bb362f/.env#L59-L65

It seems like it can be deleted.

**Comment by nsarrazin** [comment]
Indeed, good catch thanks.

**Comment by nsarrazin** [comment]
Fixed with [6d6d116](https://github.com/huggingface/chat-ui/commit/6d6d116abb8d0bc70ad220c4079d7b946e2ba5ef)
