### ISSUE TITLE
chat-ui behind proxy

### ISSUE THREAD

**Issue by ran-haim** [huggingface/chat-ui#1612]
I am unable to run chat-ui behind istio.
I didn't find a way to set baseurl, so all links/redirects are broken.

**Comment by evalstate** [comment]
You need to set APP_BASE at build time to configure the base path - so a rebuild with that set should fix it?

**Comment by ran-haim** [comment]
From what I've seen /chat is the default...not all links/redirects are /chat - i've also seen /_app.

**Comment by nsarrazin** [comment]
The default is `/` actually. For HuggingChat we use `/chat` and we set a custom build argument `APP_BASE` as you can see [here](https://github.com/huggingface/chat-ui/blob/ff9a4ce53ecf99bf7643f4ae9cb413e1a7b4983b/.github/workflows/deploy-prod.yml#L49).

You could build the image yourself with a custom `APP_BASE` that suits your needs. The assets will then be behind `${APP_BASE}/_app`, see for example on HuggingChat: `https://huggingface.co/chat/_app/immutable/entry/start.Ba9czHTP.js`

**Comment by ran-haim** [comment]
this works, but you also need to set PUBLIC_ORIGIN env variable.
thanks!

**Comment by chichur** [comment]
@nsarrazin Will this bug be fixed in the next versions? I wouldn't want to have to rebuild the application every time.
