### ISSUE TITLE
Help wanted: Installing `@huggingface` package from NPM registry

### ISSUE THREAD

**Issue by eertmanhidde** [huggingface/chat-ui#202]
👋🏻 

Sorry if I am opening a dumb issue but I was just looking into fixing some UI issues and not entirely sure how to run this project locally. I've created a `.env.local` with:
```
MONGODB_URL= 
HF_ACCESS_TOKEN=XXX
```
Haven't actually set the `MONGODB_URL` but did create an access token for HF.

Running into the following error when running `yarn`
```
yarn install v1.22.11
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@huggingface/shared@*" required by "@huggingface/inference@^2.2.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I suppose I need a secret or something for Yarn to be able to fetch that package from a different registry than NPM?

**use NPM instead of Yarn?**
Yes, I've also tried using NPM, ran into the same issue.

Again sorry if I am mistaking the readme and doing things wrong.

Thanks! 👋🏻

**Comment by Grsmto** [comment]
Hey @eertmanhidde thanks for wanting to contribute! It's an issue with the dependency https://github.com/huggingface/huggingface.js we are looking into it!

**Comment by coyotte508** [comment]
@eertmanhidde You need to use `pnpm`, not `yarn`

**Comment by eertmanhidde** [comment]
@coyotte508 yeah I've did that already, experienced the same issue.
