### ISSUE TITLE
deploy in vercel

### ISSUE THREAD

**Issue by dominicdev** [huggingface/chat-ui#212]
I'm trying to deploy this in vercel, it was success but getting this page , any solution?
I set the output to build, or this app is not possible to deploy in vercel?
![image](https://github.com/huggingface/chat-ui/assets/3959917/f187890d-85c5-4b23-aaec-16ea7dfaf78e)

**Comment by coyotte508** [comment]
Maybe you need to switch to `adapter-vercel`: https://kit.svelte.dev/docs/adapter-vercel ?

**Comment by fredguth** [comment]
Here is how I did (I hope it is useful):
```
import adapter from "@sveltejs/adapter-vercel";
import { vitePreprocess } from "@sveltejs/kit/vite";
import dotenv from "dotenv";
import pkg from "./package.json" assert { type: "json" };

dotenv.config({ path: "./.env.local" });
dotenv.config({ path: "./.env" });

process.env.PUBLIC_VERSION = pkg.version.replace(/\.0\b/g, "");

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		adapter: adapter({
			// see the 'Deployment configuration' section below
		}),

		paths: {
			base: process.env.APP_BASE || "",
		},
	},
};

export default config;
```

**Comment by dominicdev** [comment]
thanks I will try this, also what will be the output? will be build folder?

**Comment by dominicdev** [comment]
@fredguth im getting this

**Comment by fredguth** [comment]
Another point... you have to add your environment variables to the project in Vercel's dashboard (I guess there is a way via CLI).

**Comment by fredguth** [comment]
I think this issue can be closed.

**Comment by nsarrazin** [comment]
@fredguth closing this indeed.

@dominicdev feel free to reach out if you still need help with this and I will reopen it

**Comment by BEpresent** [comment]
> @fredguth im getting this what could be the problem? ![image](https://user-images.githubusercontent.com/3959917/238106324-e3052eab-d56c-49cc-a0e5-3d0f9cc5b9d5.png)

Have the same issue.

* I have used the vercel adapter in svelte.config.js
* added all .env variables In Vercel
* have a mongodb cloud instance `MONGODB_URL=mongodb+srv://xxx:pw@cluster0.xxx.mongodb.net/?retryWrites=true&w=majority`


The app runs locally with no problems. I wonder if it's the initial startup time that takes a few seconds?

This might lead to a timeout of the serverless functions on the free Vercel tier. I notice that even locally the start is not not instant but there is some delay. Could this be the issue?

Note that the only change from the default app is the models part in the `.env`, using a custom endpoint.

```
MODELS=`[
  {
    "name": "TheBloke/OpenOrca-Preview1-13B-GPTQ",
    "description": "A good alternative to ChatGPT",
    "userMessageToken": "<|### Instruction|>",
    "assistantMessageToken": "<|### Response|>",
    "messageEndToken": "</s>",
    "preprompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n-----\n",
    "parameters": {
      "temperature": 0.7,
      "top_p": 0.95,
      "repetition_penalty": 1.2,
      "top_k": 50,
      "truncate": 1000,
      "max_new_tokens": 1024
    },
"endpoints": [{"url": "endpointURL"}]
  }
]`
```

**Comment by fredguth** [comment]
> This might lead to a timeout of the serverless functions on the free Vercel tier. I notice that even locally the start is not instant but there is some delay. Could this be the issue?

In vercel the app does not work at all?  I have seen problems with an inference endpoint that was too slow for vercel, but normally this would happen while trying to use the app (messaging).

If the error is before anything... I would double check if you have all the needed KEYS in the environment.

**Comment by BEpresent** [comment]
> > This might lead to a timeout of the serverless functions on the free Vercel tier. I notice that even locally the start is not instant but there is some delay. Could this be the issue?
> 
> In vercel the app does not work at all? I have seen problems with an inference endpoint that was too slow for vercel, but normally this would happen while trying to use the app (messaging).
> 
> If the error is before anything... I would double check if you have all the needed KEYS in the environment.

So it deploys without errors, however then I get the timeout screen from above. Vercel allows copy&pasting the whole env file that I have defined locally and extracts these. The error messages are not very helpful on the Vercel side to debug the issue. My best guess is that the initial startup exceeds 10 seconds which is the max timeout limit on the vercel free tier  (locally the UI loads in ~4-5 seconds, also not instant)

This is a screen of the env variables being recognized:

<img width="399" alt="image" src="https://github.com/huggingface/chat-ui/assets/7645717/c47e1575-be8f-468f-8e72-e9a1623a0a85">
<img width="578" alt="image" src="https://github.com/huggingface/chat-ui/assets/7645717/b1b44df8-bfd9-4829-8d5f-897263afb67d">

Now when I go to the live url it times out 
<img width="779" alt="image" src="https://github.com/huggingface/chat-ui/assets/7645717/94e14922-1181-4d0f-8433-466b217b8ca8">
<img width="1597" alt="image" src="https://github.com/huggingface/chat-ui/assets/7645717/58d56615-80b9-4379-914c-365858d5d153">

**Comment by plonai** [comment]
@BEpresent I am having the same issue, did you get this to work?

**Comment by BEpresent** [comment]
> @BEpresent I am having the same issue, did you get this to work?

Unfortunately not, as mentioned my guess would be that the initial startup time that causes a timeout on Vercel serverless. Another provider might be an alternative but I have not tried this yet.

**Comment by plonai** [comment]
> > @BEpresent I am having the same issue, did you get this to work?
> 
> Unfortunately not, as mentioned my guess would be that the initial startup time causes a timeout on Vercel serverless. Another provider or a Vercel paid tier might be an alternative but I have not tried this yet.

Oh, I actually fixed it, my MongoDB database didn't include 0.0.0.0/0 in the allowed IP addresses list, so it couldn't be accessed from Vercel. It does suck that the error was not showing at all. Maybe you have the same issue

**Comment by BEpresent** [comment]
> > > @BEpresent I am having the same issue, did you get this to work?
> > 
> > 
> > Unfortunately not, as mentioned my guess would be that the initial startup time causes a timeout on Vercel serverless. Another provider or a Vercel paid tier might be an alternative but I have not tried this yet.
> 
> Oh, I actually fixed it, my MongoDB database didn't include 0.0.0.0/0 in the allowed IP addresses list, so it couldn't be accessed from Vercel. It does suck that the error was not showing at all. Maybe you have the same issue

Interesting thanks, I will try this out. Indeed, it's not apparent from the error messages.

**Comment by plonai** [comment]
> > > > @BEpresent I am having the same issue, did you get this to work?
> > > 
> > > 
> > > Unfortunately not, as mentioned my guess would be that the initial startup time causes a timeout on Vercel serverless. Another provider or a Vercel paid tier might be an alternative but I have not tried this yet.
> > 
> > 
> > Oh, I actually fixed it, my MongoDB database didn't include 0.0.0.0/0 in the allowed IP addresses list, so it couldn't be accessed from Vercel. It does suck that the error was not showing at all. Maybe you have the same issue
> 
> Interesting thanks, I will try this out. Indeed, it's not apparent from the error messages.

Did it work? 
Also, I noticed that the vercel serverless function times out after 10 seconds, so it couldn't continue streaming the response when using a self-hosted model. I am using the huggingface inference API now.

**Comment by mhenrichsen** [comment]
If anyone finds a solution to this, please post it :) Seems like a massive problem to deploy this anywhere.

**Comment by PixelVerseIT** [comment]
yeah i can't deploy to vercel
