### ISSUE TITLE
Upload an Image file

### ISSUE THREAD

**Issue by overvalue** [huggingface/chat-ui#217]
![image](https://github.com/huggingface/chat-ui/assets/121876198/3cbc668c-511b-46ce-bcfe-0d7390e6a9bc)
No option to upload an image file but the ai asks to upload an image.

(1) Either allow us to post images to on the chat 
(2) Restrict that and say the ai can't do it or something like that

**Comment by ALIRAZA17** [comment]
@overvalue can I work on this issue?

**Comment by overvalue** [comment]
Hm

**Comment by julien-c** [comment]
@ALIRAZA17 yes feel free to work on a pull request – note that we don't have a good multimodal LLM for now, but it will be useful to have the UI anyways

**Comment by ALIRAZA17** [comment]
ok im on it!

**Comment by cfregly** [comment]
@ALIRAZA17 would you mind generalizing this to any binary content?  ie. PDF's, etc?

**Comment by ALIRAZA17** [comment]
@cfregly Yeah Im on it I'll try if its possible!!

**Comment by ALIRAZA17** [comment]
> ![image](https://user-images.githubusercontent.com/121876198/238142223-3cbc668c-511b-46ce-bcfe-0d7390e6a9bc.png) No option to upload an image file but the ai asks to upload an image.
> 
> (1) Either allow us to post images to on the chat (2) Restrict that and say the ai can't do it or something like that

@overvalue Can you tell where is this option because Ive run the application on localhost and couldn't find the upload image option?

**Comment by overvalue** [comment]
I did not get it , wdym by which option @ALIRAZA17

**Comment by trojan03** [comment]
Any update on this?

**Comment by gary149** [comment]
Something like this will come with a future update 👀

**Comment by jackbravo** [comment]
Seems like this is being worked on at PR #641, that references issue #609
