### ISSUE TITLE
Support for Contrastive Search?

### ISSUE THREAD

**Issue by PhNyx** [huggingface/chat-ui#218]
Context: https://huggingface.co/blog/introducing-csearch

Passing only:

    "penalty_alpha":0.6,
    "top_k": 4,

Does not seem to work, as truncate, and temperature is still required.  When passing this:
<pre>

 "parameters": {
    "temperature": 0.9,
    "penalty_alpha":0.6,
    "top_k": 4,
    "truncate": 512,
    "max_new_tokens": 512
  }
</pre>

penalty_alpha seems to be ignored:

GenerateParameters { best_of: None, temperature: Some(0.9), repetition_penalty: None, top_k: Some(4), top_p: None, typical_p: None, do_sample: false, max_new_tokens: 512, return_full_text: Some(false), stop: [], truncate: Some(512), watermark: false, details: false, seed: None } })

**Comment by coyotte508** [comment]
cc @OlivierDehaene maybe?

**Comment by OlivierDehaene** [comment]
Contrastive search is not supported by text-generation-inference.
