### ISSUE TITLE
Adding support for conversation threads

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#223]
Might be valuable to allow the user to branch out into separate slack-like threads. This lets you keep the main convo rolling while allowing you to dig deeper into a specific answer.

<img width="387" alt="image" src="https://github.com/huggingface/chat-ui/assets/25119303/b43bba0a-c902-472e-ab91-9e2e1f6c74a9">

**Comment by SvCy** [comment]
In this case, thread/branch deletion by deleting a message/prompt would be good too, i think. After all we don't wanna make things bloated!

**Comment by secondtruth** [comment]
I like this idea! Could be a major improvement. 👍

**Comment by SvCy** [comment]
@gary149 while the icon looks good, I think branching should be on by default. If we get edit feature, that should branch out this way too. This icon can be placed on the numbers of branches & in navigation.

**Comment by gary149** [comment]
> @gary149 while the icon looks good, I think branching should be on by default. If we get edit feature, that should branch out this way too. This icon can be placed on the numbers of branches & in navigation.
But in any case, we need to get branching out feature this way or another. ✨

Yes that's what I meant.
