### ISSUE TITLE
Special tokens for user and assistant turns?

### ISSUE THREAD

**Issue by frandominguezl** [huggingface/chat-ui#225]
Hi,

I've been checking the example that used `OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5` model. This model uses the following tokens to specify the beginning of the user and assistant:

```
"userMessageToken": "<|prompter|>",
"assistantMessageToken": "<|assistant|>"
```

I'm trying to run `bigcode/starcoder` model along with `bigcode/the-stack-dedup` dataset, but I'm not sure which values do those variables need for this particular model and how they influence the model's answer generation.

Could you please briefly guide me into this? I'm kinda new to this.

**Comment by coyotte508** [comment]
Here's the configuration for bigcode / starcoderbase:

```
{
  "name":"bigcode/starcoderbase",
  "displayName":"BigCode/StarCoderBase",
  "datasetName":"bigcode/the-stack-dedup",
  "description": "A good model for answering technical questions",
  "websiteUrl":"https://huggingface.co/bigcode/",
  "prepromptUrl": "https://huggingface.co/datasets/coyotte508/bigcodeprompt/raw/main/prompt.txt",
  "promptExamples": [
    {
      "title": "Write a code snippet",
      "prompt": "Write a function that loads a file and filters line starting with \"Star\"?"
    }, {
      "title": "Explain a technical concept",
      "prompt": "What is a Dockerfile?"
    }, {
      "title": "Solve a technical task",
      "prompt": "How to install pytorch with cuda?"
    }
  ],
  "userMessageToken": "\n\nHuman: ",
  "assistantMessageToken": "\n\nAssistant:",
  "parameters": {
    "temperature": 0.1,
    "top_p": 0.9,
    "repetition_penalty": 1.2,
    "truncate": 8000,
    "max_new_tokens": 2000,
    "stop": ["Human:", "-----", "Assistant:"]
  }
}
```

**Comment by frandominguezl** [comment]
Thank you for the super-fast answer. Was this available somewhere and I didn't find it or it was just a mere lack of knowledge by myself?

**Comment by coyotte508** [comment]
It was available for some time on hf.co/chat, but was removed: https://github.com/huggingface/chat-ui/pull/187

(because the model is not that great at chat)
