### ISSUE TITLE
Unknown flag in DockerFile

### ISSUE THREAD

**Issue by knoel99** [huggingface/chat-ui#231]
An error occurred when running the following command:
`docker build -t chat-ui .`

<img width="1139" alt="image" src="https://github.com/huggingface/chat-ui/assets/36934762/07a645a5-a0a0-44db-a89c-0377523f980c">
<img width="525" alt="image" src="https://github.com/huggingface/chat-ui/assets/36934762/f808f68e-4ee7-476b-9ab7-9638c951d01c">

**Comment by coyotte508** [comment]
It's your version of docker that's not recent enough

**Comment by knoel99** [comment]
Your are right thank you
