### ISSUE TITLE
Possible performance regression in the production model?

### ISSUE THREAD

**Issue by overvalue** [huggingface/chat-ui#232]
I have been using it for 5 days , it could write  simple codes for me  but now it can't ;/

**Comment by gary149** [comment]
Can you elaborate on what changed?

**Comment by osanseviero** [comment]
Maybe @overvalue was using Starcoder and now they are using OA model

**Comment by overvalue** [comment]
> Can you elaborate on what changed?

So I was using the program to write some simple discord bot codes in different languages but now if you try it can't do that for you.

**Comment by gary149** [comment]
> Maybe @overvalue was using Starcoder and now they are using OA model

Do you know what model was selected @overvalue?

**Comment by overvalue** [comment]
Nope I dont know @gary149 i just use to open the website and just go ask the things , the login thing was not implemented at that time.
