### ISSUE TITLE
Documentation Request - Clarity around login flow outside of HuggingFace context

### ISSUE THREAD

**Issue by hack-r** [huggingface/chat-ui#246]
Could the docs (if not the code) be improved to make it clear how to:

- run this without requiring users to authenticate
- handle authentication via a 3rd party cloud (Azure, AWS, GCP, etc)
- run this with an arbitrary 3rd party model (OpenAI, Rasa, etc)

I originally thought this was the purpose of `OPENID_CLIENT_ID` and `OPENID_CLIENT_SECRET`, but it seems not... (?).

**Comment by coyotte508** [comment]
There is no need to have users authenticate if `OPENID_CLIENT_ID` and `OPENID_CLIENT_SECRET` are not specified.

> handle authentication via a 3rd party cloud (Azure, AWS, GCP, etc)

The three parameters `OPENID_CLIENT_ID`, `OPENID_CLIENT_SECRET` and `OPENID_PROVIDER_URL` need to be specified.

For example https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/auth-oidc, you just need to enable OIDC with Azure / AWS / GCP / ... and specify the three params

**Comment by hack-r** [comment]
🙏👍

**Comment by nsarrazin** [comment]
We updated the readme with #264 so hopefully it's clearer in the future! Closing this for now, feel free to reopen if I missed something.
