### ISSUE TITLE
UI refactor for menu items

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#247]
![image](https://github.com/huggingface/chat-ui/assets/25119303/cac249f0-40e5-4265-9964-c6e05852b9fa)

It's hard to distinguish between past chats and the menu items when the bar is full. I think a low hanging fruit would be to add:
* A horizontal separator between the two
* Icons for the menu tabs 
* Maybe play around with the typography, increasing font weight on menu items for example.

**Comment by coyotte508** [comment]
See also https://github.com/huggingface/chat-ui/issues/143

**Comment by fredguth** [comment]
I also would move Theme inside Settings.

**Comment by gary149** [comment]
Closing, will probably do a V2 redesign at some point.
