### ISSUE TITLE
disable login on free plan

### ISSUE THREAD

**Issue by fusionneur** [huggingface/chat-ui#262]
until recently i was able to use huggingface (free plan) without logging in (no account). there should be no wall for people to use it and also it should be usable anonymously (even via tor) to prevent privacy concerns.

**Comment by Apaczer** [comment]
Earlier I've found it  very convenient to share chats/snippets between different devices without need to login (from share url feature). It was disitnctive from other platforms for hugginface to not have a login wall at first.

**Comment by nsarrazin** [comment]
Hey! If you want to setup your own version without logging in you can absolutely do it, as the full stack used for huggingchat is open-sourced. The source for the generation endpoint is available from: https://github.com/huggingface/text-generation-inference and of course the front-end is available on this repo. :smile: 


@Apaczer indeed, shared conversations should probably be visible without having to log in. I've opened a separate issue [here](https://github.com/huggingface/chat-ui/issues/266).

**Comment by fredguth** [comment]
I have to test... but I guess that if you don't include OPENID_CLIENT and ...SECRET in any .env, it will not ask for login.  I will check this later.

**Comment by julien-c** [comment]
@fredguth is correct
