### ISSUE TITLE
[question] Where should we discuss chat-ui roadmap?

### ISSUE THREAD

**Issue by fredguth** [huggingface/chat-ui#263]
Is there a forum to discuss future features?

I need to implement some sort of UI component for answer references.  Something like perplexity.ai "pills" under the answer.
I guess this is useful for others and I would like to discuss how should I implement such thing before hand.
- should I use pills?
- should I create a special message component?
- maybe horizontal scrolling on "facts"/references?

Is there a place for this kind of discussion?  Am I the only one with this demand?

**Comment by gary149** [comment]
Regarding future features, I started a discussion on the HF Hub ( I added some screenshots for the websearch as there are some kinds of pills there.): https://huggingface.co/spaces/huggingchat/chat-ui/discussions/176

For your use case, have you tried to fork it on your side to implement it? Adding a Pill component should be relatively straightforward.
