### ISSUE TITLE
Shared conversations should not require a login

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#266]
Currently if you try to access a shared conversation and the `.env` is setup to support logging in, you will have to login before you can see it.

Since shared convos are read only, it makes sense to be able to see them without logging in first.

**Comment by jakelevirne** [comment]
It looks like there's a regression here. When sharing a chat from https://huggingface.co/chat/ (or from a self-hosted chat-ui server with OPENID enabled), the recipient of the shared link is required to authenticate before being able to view the shared chat.

I'm wondering if this was intentional?

**Comment by nsarrazin** [comment]
Nope it's a regression, thanks for catching it! Will take a look
