### ISSUE TITLE
Documentation about how to configure custom model endpoints is missing

### ISSUE THREAD

**Issue by djmaze** [huggingface/chat-ui#273]
It seems it has been removed in https://github.com/huggingface/chat-ui/commit/fae93d9fc3be9a39d8efd9ab9993dea13f0ae844.

**Comment by nsarrazin** [comment]
Thanks for opening an issue. I'm not sure what the issue is, could you tell me what you're missing from https://github.com/huggingface/chat-ui#custom-models ?

**Comment by djmaze** [comment]
The `endpoints` key in the `MODELS` variable is not documented anymore.

**Comment by averad** [comment]
@nsarrazin 

```
Running your own models
If you want to, you can even run your own models, by having a look at our endpoint project, [text-generation-inference](https://github.com/huggingface/text-generation-inference). You can then add your own endpoint to the MODELS variable in .env.local and it will be picked up as well.
```
As described above the endpoints key is not documented on either the chat-ui or text-generation-inference documentation.
