### ISSUE TITLE
Button to continue generation 

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#280]
Sometimes the model stops early when generating. It should be fairly easy to add a "continue generation" button to help unstuck the answer when that happens.

It's been requested quite a bit on the [space](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/179#647ec5c532c471a7faa593c6).

**Comment by nsarrazin** [comment]
I think the idea I had in mind was more that in case the model finishes early, when you click the button you prompt it again up-to and including the message it already has generated so far. (While stripping the message end token) 

That way it should continue generating things where it left off in the same message

**Comment by gary149** [comment]
Ok I think that could work, ChatGPT:
<img width="506" alt="image" src="https://github.com/huggingface/chat-ui/assets/3841370/27dfad56-ea54-47a3-947a-0aadc7415500">

**Comment by hungryalgo** [comment]
@nsarrazin As many have pointed out, this is a major and very common issue. 
Roughly when would we see a fix? If not by say second quarter next year, I want to help putting in a fix.
