### ISSUE TITLE
OpenID login

### ISSUE THREAD

**Issue by sankethgadadinni** [huggingface/chat-ui#282]
How to get providerURL, client ID and client token to create azure openid login?????

**Comment by nsarrazin** [comment]
Hey! These environment variables must come from your openID login provider. For example [with Google OpenID Connect.](https://developers.google.com/identity/openid-connect/openid-connect#getcredentials)

Not sure specifically about azure, but it should be similar. You don't need these variables to run chat-ui though, if you don't have an openID provider set up,  it will just create unique ids for each browser that uses chat-ui.
