### ISSUE TITLE
Facing issue for using custom model deployed locally on flask

### ISSUE THREAD

**Issue by awsum0225** [huggingface/chat-ui#295]
I have a chat model which responds on
```
@app.route("/get")
#function for the bot response
def get_bot_response():
    userText = request.args.get('msg')
    data = T.getResponse(userText)
    return str(data)
```

I'm not sure about the configuration but I have added `MODELS=[{"name": "mymodel", "endpoints": [{"url": "http://127.0.0.1:5000/get"}]}]` in the` .env.local` file

Getting following error:
![image](https://github.com/huggingface/chat-ui/assets/39643649/f3717b0b-de67-4b19-9a57-a6531c52c93c)

Can someone please help me to configure my local model with HuggingChat chat-ui

**Comment by nsarrazin** [comment]
Hey! I think the endpoint is supposed to be a [text-generation-inference](https://github.com/huggingface/text-generation-inference) endpoint... You could try to use that and see if that solves your problem ?

**Comment by awsum0225** [comment]
Hey @nsarrazin  thanks for the reply!
Sorry if I'm being very obvious here, in order to implement our own python code of a model (in my case I have trained using langchain llama which answers questions from a set of documents whichI have trained on) are we supposed to make that code in compliance with [text-generation-inference](https://github.com/huggingface/text-generation-inference) codebase. Would appreciate a helping had over here. Thanks

**Comment by nsarrazin** [comment]
No worries! Sounds like a cool project, and yeah I think you have to mock the API of text-generation-inference, as chat UI was designed to use it initially.

I'm not too familiar with the implementation details of TGI but a few pointers:
* Someone made [a wrapper for integrating the openAI API with chat-ui](https://github.com/gururise/openai_text_generation_inference_server), maybe the code there could help you out? 
* The API definition for TGI is available [here](https://huggingface.github.io/text-generation-inference/#/) with all the endpoints & parameters.

Let me know if that helps. :smile:

**Comment by awsum0225** [comment]
Thanks again @nsarrazin 
This looks very helpful, would let you know how it goes. Cheers!

**Comment by NielsRogge** [comment]
Hi @awsum0225,

the text-generation-inference package supports a [selected list of models](https://github.com/huggingface/text-generation-inference#optimized-architectures), which includes LLaMa. Hence if you fine-tuned LLaMa on your own dataset for instance, then it's supported).

You just need to provide the appropriate `--model-id` when running the Docker image: https://github.com/huggingface/text-generation-inference#docker. The Docker image assumes that the model is hosted on the HF hub.

**Comment by awsum0225** [comment]
> No worries! Sounds like a cool project, and yeah I think you have to mock the API of text-generation-inference, as chat UI was designed to use it initially.
> 
> I'm not too familiar with the implementation details of TGI but a few pointers:
> 
>     * Someone made [a wrapper for integrating the openAI API with chat-ui](https://github.com/gururise/openai_text_generation_inference_server), maybe the code there could help you out?
> 
>     * The API definition for TGI is available [here](https://huggingface.github.io/text-generation-inference/#/) with all the endpoints & parameters.
> 
> 
> Let me know if that helps. 😄

This was helpful! Thanks
