### ISSUE TITLE
Issue when deploying model : Error in 'stream': 'stream' is not supported for this model

### ISSUE THREAD

**Issue by samichaignonmejai** [huggingface/chat-ui#296]
I'm trying to use bigscience/bloom-560m with chat-ui
I already have an API for the model and it's working well, same for chat-ui when I use my HF token but i get the following error message when I launch a request to my bloom-560m API from chat-ui :

```
Could not parse last message {"error":["Error in `stream`: `stream` is not supported for this model"]}
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseGeneratedText (/src/routes/conversation/[id]/+server.ts:180:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async saveMessage (/src/routes/conversation/[id]/+server.ts:95:26)
```
I tried modifying the URL of my API from http://xxx.xxx.x.xxx:8080/generate_stream to http://xxx.xxx.x.xxx:8080/generate but it is not working as well ... any thoughts about this ?

**Comment by nsarrazin** [comment]
Hey, thanks for filing a report! I'd like to help out, it seems like the specific model you want to run doesn't support streaming. If you have the right hardware could you try something like [this model](https://huggingface.co/OpenAssistant/falcon-7b-sft-top1-696) ?

And I think it would be nice to support non streaming models in chat-ui, I'll have to look to see if it's easy to do.
