### ISSUE TITLE
Is there a way to deploy without the HF token ?

### ISSUE THREAD

**Issue by samichaignonmejai** [huggingface/chat-ui#297]
I'm trying to use chat-ui with my own endpoints and I would like to know if I can get rid of the HF_ACCESS_TOKEN variable and also allow to run every model I want. 

I tried to modify the TS in modelEndpoint.ts and model.ts but I can't figure how to run it independently to HF (I want it offline), here are the parts I suspect to prevent me from doing it :

modelEndpoint.ts :
```
if (!model.endpoints) {
		return {
			url: 'https://api-inference.huggingface.co/models/${model.name}',
			authorization: 'Bearer ${HF_ACCESS_TOKEN}',
			weight: 1,
		};
	}
```
model.ts :
```
endpoints: z
.array(
	z.object({
		url: z.string().url(),
		authorization: z.string().min(1).default(`Bearer ${HF_ACCESS_TOKEN}`),
		weight: z.number().int().positive().default(1),
	})
)
```
Any thoughts about this ?

**Comment by nsarrazin** [comment]
The token is needed if you're using our hosted endpoints, but for running it locally you can spin up your own models inference endpoint using https://github.com/huggingface/text-generation-inference in which case you won't need any tokens/authentication I think.

Let me know if that answered you question!
