### ISSUE TITLE
Using HuggingChat in a JavaScript/node.js setting?

### ISSUE THREAD

**Issue by VatsaDev** [huggingface/chat-ui#299]
Hi, I'm not sure whether this is relevant here, but I'd like to use the HuggingChat in a personal web design project, and I'd like to access it through REST/axios, similar to this [here](https://stackoverflow.com/questions/75714587/node-js-turn-hugging-face-image-response-to-buffer-and-send-as-a-discord-attac) (stable diffusion hugging face example)

So far the only thing I could find was the [huggingChat python](https://github.com/Soulter/hugging-chat-api), and I'm not really sure how to use that in what I'm looking for. Can anyone help?

**Comment by nsarrazin** [comment]
Hey! I opened an issue (#307 ) to add some API documentation. In the meantime is there something I can do to help out with your project specifically ?

You can check the available routes in the app here: https://github.com/huggingface/chat-ui/tree/main/src/routes

And each file in these directories that is called `+server.ts` contains API endpoints. You can read more about them in the https://kit.svelte.dev/docs/routing#server here.

**Comment by VatsaDev** [comment]
So far, I've been using the [python_Api](https://github.com/Soulter/hugging-chat-api), and I'm getting the 500 model overloaded error 9/10 prompts. is that regular about the server? or is it because of the python Api

**Comment by gary149** [comment]
#307 will fix this, giving your documented API endpoints.
