### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by Muennighoff** [huggingface/chat-ui#304]
How do code blocks like img attached work under the hood?

Is it the model that generates ``` & it gets detected and converted to code?
Or is it the UI/Backend that detects code and converts it to look like a code block?

<img width="434" alt="Screenshot 2023-06-17 at 3 26 39 PM" src="https://github.com/huggingface/chat-ui/assets/62820084/d5b79272-d3d9-46c5-9761-e38515f3c73c">

**Comment by nsarrazin** [comment]
We use a markdown parser (`marked`) which gives us tokens representing code blocks and we format these using the `CodeBlock` component.

See more here:

* https://github.com/huggingface/chat-ui/blob/e34af3608b23bda963bd4f93a063fb03f20be81b/src/lib/components/chat/ChatMessage.svelte#L61-L76 
* https://github.com/huggingface/chat-ui/blob/main/src/lib/components/CodeBlock.svelte

Let me know if that answered your question!

**Comment by Muennighoff** [comment]
> We use a markdown parser (`marked`) which gives us tokens representing code blocks and we format these using the `CodeBlock` component.
> 
> See more here:
> 
> * https://github.com/huggingface/chat-ui/blob/e34af3608b23bda963bd4f93a063fb03f20be81b/src/lib/components/chat/ChatMessage.svelte#L61-L76
> * https://github.com/huggingface/chat-ui/blob/main/src/lib/components/CodeBlock.svelte
> 
> Let me know if that answered your question!

I see so the model does not need to know when to generate ```, but it's done automatically right?

**Comment by nsarrazin** [comment]
The model does need to know when to generate the ``` and then they get parsed by the markdown parser, otherwise they would be no way to know I think.
