### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by Toaster496** [huggingface/chat-ui#313]
I have a free teir MongoDB acount but not sure how to get url plz help

**Comment by nsarrazin** [comment]
Hey! The format used for connecting to mongoDB can be found [here](https://www.mongodb.com/docs/manual/reference/connection-string/).

basically: `mongodb://[username:password@]host1[:port1/[defaultauthdb][?options]]` 

Let me know if that helped!

**Comment by Toaster496** [comment]
is like this? mongodb+srv://Toaster496:***************@chat-ui.p3akqsn.mongodb.net/

**Comment by Toaster496** [comment]
thanks

**Comment by nsarrazin** [comment]
Yeah that should be the format. Glad it helped!

**Comment by Toaster496** [comment]
i donno what im dooing wrong. https://huggingface.co/spaces/Toaster496/chat-ui-3.0
