### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by kasinadhsarma** [huggingface/chat-ui#314]
![image](https://github.com/huggingface/chat-ui/assets/81065703/33c28e7b-584b-48e3-a64c-b4d5271a325f)

**Comment by nsarrazin** [comment]
Hi! I'm going to need a few details so I can help you out.

* Was this error on huggingchat (the hosted website) or your own instance of ChatUI ?
* If it's your own, are you running it locally or on the cloud? What are the specs ? (OS, architecture)
* What kind of database are you using ?

And if you could send me any logs you had with this error, that would be great! Then I can try to figure out what's wrong.

**Comment by kasinadhsarma** [comment]
1) yes 
2) kali linux , amd64
3) nothing
