### ISSUE TITLE
Issues when trying to deploy on cPanel (shared hosting)

### ISSUE THREAD

**Issue by gollumeo** [huggingface/chat-ui#317]
Hello there, 

Is there something special to do to be able to deploy chat-ui on a shared hosting using cPanel? 

I tried using the Node.JS Apps Manager as follows
![cpanel](https://github.com/huggingface/chat-ui/assets/109650634/fac1abfd-000a-4dde-bf38-54427b12889c)

But even when switching my entry point to server/index.js, it doesn't work. 

I also tried to NPM install using the manager, but then it doesn't seem to be able to use vite, even when forcing any `npm install vite`... 

So, if you could me out on this, it would be highly appreciated! 

In advance, thanks a lot. 

Regards, 

Golluméo

**Comment by gary149** [comment]
We don't use cPanel, is this still an issue?
