### ISSUE TITLE
Chat-UI not loading Tailwind colors. 

### ISSUE THREAD

**Issue by ckanaar** [huggingface/chat-ui#321]
**Problem**

When specifying `PUBLIC_APP_COLOR` in either the `.env` or the `.env.local` file, the chat-UI color does not change regardless of which color is used. Even when  `PUBLIC_APP_COLOR=blue` as set in this repository, the chat-UI color does not match with TailwindCSS's blue color palette: 

**TailwindCSS blue color palette:**
<img width="452" alt="blue" src="https://github.com/huggingface/chat-ui/assets/48559179/216923cf-6941-4629-b444-65a4930f3979">

**Chat-UI color palette:**
<img width="692" alt="chat" src="https://github.com/huggingface/chat-ui/assets/48559179/809aece3-3efe-4dd5-ac48-5cc0b6f32221">

**Observation**
Upon investigating the code, I noticed that the switchTheme.ts file contains the following code:
```
export function switchTheme() {
	const { classList } = document.querySelector("html") as HTMLElement;
	if (classList.contains("dark")) {
		classList.remove("dark");
		localStorage.theme = "light";
	} else {
		classList.add("dark");
		localStorage.theme = "dark";
	}
}
```

I think that instead of loading the Tailwind colors specified in either `.env` or `.env.local`, the chat-UI is actually using these `"light"` and `"dark"` themes. I couldn't find where these themes are specified in the repositories or if they can be changed at all. 

**Requested Solution:**
I want to load the Tailwind colors by setting `PUBLIC_APP_COLOR` in `.env` and/or `.env.local`. However, if it turns out that the chat-UI laods colors based on the  `"light"` and `"dark"`, adjusting these themes could also be a viable solution. Thank you in advance for your assistance.

**Comment by nsarrazin** [comment]
Maybe an obvious question but did you restart the vite server in between changes to the `.env.local` ? Changes are not picked up otherwise.

**Comment by ckanaar** [comment]
Yes, the vite server is restarted after making the changes.

**Comment by gary149** [comment]
PUBLIC_APP_COLOR only changes the colour of a few primary elements. You can always change the colour manually if necessary (in the html files).
