### ISSUE TITLE
Chat-ui is starting, but nothing happends

### ISSUE THREAD

**Issue by Notespeak** [huggingface/chat-ui#334]
# Description:

When starting the Chat-ui, the initialization process begins as expected but stalls indefinitely, without any evident progress. The application doesn't crash nor gives any errors. This issue occurs across multiple attempts, regardless of browser type or device.

# Steps to reproduce:
- Install prerequisites
- Fill evn.local file
- Lauch a DB container for chat persistance
- Start Chat-UI
- Open a browser (e.g., Chrome, Firefox, Safari)
- Navigate to the Chat-ui web address.
- Observe the behavior.

# Expected result:

After navigating to the url, the Chat-ui should initialize and allow for the use of its various functionalities.

# Actual result:

The UI remains in a state of 'loading' indefinitely without any change, timing out after some time.

# Environment:
This issue was reproduced on:
1. Operating System: Ubuntu 22.04, Fedora Workstation 38
2. Node Version: v18.16.1
3. NPM Version: 9.5.1

Additional context:
- No error messages are displayed.
- There is no notable console log information.
- Network status is stable during the process.
- Similar behavior noticed on Fedora.
- Refreshing the browser, clearing the cache, or using a different browser does not resolve the issue.
- Firewall is disabled on host

If you need any further information, I would be glad to provide it. Thanks in advance!

**Comment by nsarrazin** [comment]
Hi! Thanks for filing the issue, what's in your .env.local file ? Where are your models located ? That might be helpful to figure out what's going on 😄

**Comment by nsarrazin** [comment]
Closing this for now, let me know if you need further help.
