### ISSUE TITLE
[WebSearch] "Input validation error: `inputs` tokens + `max_new_tokens` must be <= 1512. Given: 1000 `inputs` tokens and 1024 `max_new_tokens`"

### ISSUE THREAD

**Issue by gollumeo** [huggingface/chat-ui#340]
Hello there, 

Title says it all. 
We are not using any custom endpoints/models. We're just relying on the HuggingFace's API inferences. 
Is there a way to increase/decrease the inputs token when using WebSearch (or even just increase the max sum)? Because it works fine if `max_new_tokens` is set to 512 BUT it, obviously, cuts any answer getting upper these numbers. 
So far, I didn't find a good balance neither how to decrease the number of tokens of the input. 

In advance, thanks for your answer! 
![image](https://github.com/huggingface/chat-ui/assets/109650634/dbc25ae1-d894-48a7-8b0c-5a0bdad33e3e)

**Comment by nsarrazin** [comment]
Hey! Thanks for bringing this up, indeed I'm not super sure why the limit is set to 1512, I will ask internally. Which model are you using with the inference endpoint ?

**Comment by gollumeo** [comment]
Hello! We're using [OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5](https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5), and will mostly migrate to another one once things will be settled down. 
Anyway, thanks for your answer! I'll wait for any update :) 

I remain available for any further question!

**Comment by nsarrazin** [comment]
Hi! So it's a default value used on the hosted API endpoints, but you can change it when hosting your own [text-generation-inference](https://github.com/huggingface/text-generation-inference) endpoint. 

See the exact parameter [here](https://github.com/huggingface/text-generation-inference/blob/b4024edd4549ab647b02b8619b4072e33e64f1f9/launcher/src/main.rs#L130-L139).

Let me know if that answered your question!

**Comment by gollumeo** [comment]
Hi! So, if I get ir right, that means that the host of the model/inference API endpoint has the control over those values, right? 
If that's right, then thanks for your answers :)

**Comment by nsarrazin** [comment]
Yes that is correct!
