### ISSUE TITLE
404 not found error when exporting data

### ISSUE THREAD

**Issue by flozi00** [huggingface/chat-ui#344]
https://github.com/huggingface/chat-ui/blob/1eff97d9fd47d8c486480d4d9a5208437c519cbb/src/routes/admin/export/%2Bserver.ts#L16

I am using the main branch and tried to export the dataset with the curl request given in the code, but the server returns 404 not found.
Its behind an reverse proxy with ssl, do i need to call the localhost or should it be possible even from outside the network ?

**Comment by nsarrazin** [comment]
Hi! Thanks for opening the issue. I tried it locally and the export functionality works fine for me on localhost. I think it might be an issue with your reverse proxy setup? Can you use the rest of the UI normally ?

**Comment by flozi00** [comment]
yes, its only the export

**Comment by nsarrazin** [comment]
If parquet was misconfigured you would get a 500 error, or maybe a 403 but a 404 seems unlikely... I think it might have to do with the reverse proxy. Can you try without it somehow ?

**Comment by flozi00** [comment]
when using localhost 404 still occurs

**Comment by thaumstrial** [comment]
> `curl -X POST "http://127.0.0.1:5173/chat/admin/export" ` Thats the path i used, is anything missing or typo inside i am not seeing ?

@flozi00
I tried "curl -X POST "http://127.0.0.1:5173/admin/export" and it works.
