### ISSUE TITLE
Can't use chat-ui in a space on the hub, while in iframe view

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#349]
Due to the recent changes to cookies in iframes done on the spaces part of the hub, chat-ui no longer works when embedded into the hub. This breaks the chatUI template for spaces currently. 

Since we don't expect the cookie situation to change on the hub we have two options:
- Make a no-cookie mode where the sessionId is being passed through headers, but we loose persistence. (but you would still have persistence if you opened the exact same url in your browser, outside of the iframe, which might be weird UX)

- Show a modal if within an iframe with a link that opens a new tab in the actual space URL.

**Comment by lhoestq** [comment]
+1, I can't use chat-ui on ios when in an iframe from a link on twitter or slack because of that

**Comment by nsarrazin** [comment]
Solved with #480 !
