### ISSUE TITLE
Starchat-beta doesn't stop generating text properly

### ISSUE THREAD

**Issue by XiaPZ** [huggingface/chat-ui#351]
Hi, I am deploying starchat-beta and chat-ui locally, it is strange that I found the chat will generate some useful text in the beginning, then it will not stop, then generates some unrelated text, like below
![Screenshot from 2023-07-19 22-23-00](https://github.com/huggingface/chat-ui/assets/7758217/a41395b1-fbe1-4632-b162-35d656ba30a0)

Is it related with .env.local configuration?
![Screenshot from 2023-07-19 22-25-01](https://github.com/huggingface/chat-ui/assets/7758217/bda3a91e-e5ce-4b7e-8b6c-e63d129dce37)

**Comment by nsarrazin** [comment]
Hey, thanks for opening the issue. I'm not sure what might be causing this, probably something to do with the `messageEndToken` in your `MODELS` var.... Maybe try to check if it's correct ? I'll check on my side as well

**Comment by XiaPZ** [comment]
> 

sure, thanks

**Comment by XiaPZ** [comment]
after check with https://huggingface.co/spaces/HuggingFaceH4/starchat-playground/tree/main, seems the `stop` field in parameters should be set as <|end|>, then it behaves normal.
![Screenshot from 2023-07-20 13-34-37](https://github.com/huggingface/chat-ui/assets/7758217/6de9fc2c-e1fb-476a-9640-19ec83bc2b34)
