### ISSUE TITLE
Broken encoding for Korean and possibly other languages

### ISSUE THREAD

**Issue by cceyda** [huggingface/chat-ui#358]
I was testing the llama2 and noticed there are some encoding errors (Ignore that the output is total nonsense):
<img width="1618" alt="image" src="https://github.com/huggingface/chat-ui/assets/15624271/61868780-efa0-4670-84d9-734410a05451">
I though It could be because of weird mid-unicode tokenization but I also noticed this on a custom demo using huggingchat ui:

It renders correctly & strangely enough breaks and unbreaks randomly.

https://github.com/huggingface/chat-ui/assets/15624271/7b7e97cb-876d-47cc-b89d-aabebb9197cf

**Comment by cceyda** [comment]
Also the last charachter of prompts in korean remains in the input box. Only when typing, not copy paste.
"한국어 번역해줘"

https://github.com/huggingface/chat-ui/assets/15624271/08c45c1e-f9df-4071-945c-d2ea55f3a9ad

**Comment by julien-c** [comment]
this might be at the model level though. Is this llama2?

**Comment by cceyda** [comment]
- The first image is from llama2 on huggingface/chat. Yes, this is most likely because of tokenization/model. Sad to see llama2 fails so badly...generating invalid unicode sequences 🤔  From a research/model understanding POV It might be nice to see what unicode it generates like <u+1234> instead of <?>, though as a user <?> makes more sense.

- The second video where the encoding randomly breaks is more interesting, because it generates correctly and breaks after finishing generating (and sometimes recovers later on). I'm guessing it might have to do with markdown renderer. This is from a custom demo using (pretty sure a) chat-ui fork, though I'm not sure which version. Guess I'll have to wait until they release officially. Might be a good idea to add the UI version somewhere into the html tags.

- The input box character issue is on huggingface/chat. Upon further testing seems to be an mac+chrome issue. Works fine with windows+chrome & mac+safari 🤷‍♀️ Maybe just my notebook is cursed today 🤣 And I haven't even tried breaking llama with emojis yet
