### ISSUE TITLE
When starting with build files, it becomes impossible to change the model.

### ISSUE THREAD

**Issue by TaskeHAMANO** [huggingface/chat-ui#363]
When starting with pm2 following the Docker file's instructions, I encounter an issue where I cannot change the model. Specifically, after clicking on "Current Model," a popup to select the model appears, but even after selecting "Apply," no changes are observed. Upon inspecting the developer tools, I noticed a 403 Error for http://localhost:3000/settings. This problem occurs both when hosting the software on a Docker container and when deploying it directly.
![image](https://github.com/huggingface/chat-ui/assets/7141702/ed16edd1-ebe5-4b1f-b47e-c6be1c380ccf)

Also, I have confirmed that this error does not occur when using `npm run dev` or `npm run preview`. Therefore, I suspect that this issue may be related to pm2. If someone has any hints or insights that could help resolve this problem, I would greatly appreciate comments.

My environment is as follows:
OS: Windows 10 + WSL 2 (Ubuntu 20.04)
Node Version: 18.15.0
Commit ID: 569bde33470b075bf1365af2cb03a1b31b875379

**Comment by TaskeHAMANO** [comment]
It turns out that the issue is not caused by pm2.
Today, I thought of trying to run the software without using pm2, so I started it with `node build/index.js` for verification. However, I confirmed that the same error occurs as when starting it with pm2...

**Comment by TaskeHAMANO** [comment]
The issue with this bug was the lack of support for HTTP connections. 
From the error message in the developer tools indicating an SSL authentication failure, I deduced that the cause of the problem could be the HTTP connection to the Node application running on pm2. Therefore, I set up a nginx container and reconfigured it to connect to the Node application via a reverse proxy with HTTPS. As a result, I was able to select the model without any problems. 
I hope this will serve as a useful reference for those who intend to operate in a similar production environment.

To the developers, I have a question. Are there any plans to make the built Node application, which is running on port 3000, accessible directly? If it's difficult to implement, feel free to close this issue.

**Comment by nsarrazin** [comment]
We don't really expect to expose the node app directly but you could make your own dockerfile to do so!

**Comment by jsccast** [comment]
@nsarrazin or @TaskeHAMANO , what's the simplest possible way to get direct HTTP access when running Docker to work? (Direct access over HTTP used to work, and it was handy for experiments.)

(A symptom of the problem is that `/settings` update results in a 403.)
