### ISSUE TITLE
Ability to pass in request headers for model endpoints

### ISSUE THREAD

**Issue by lotif** [huggingface/chat-ui#368]
Hello.

I am trying to add an AWS Sagemaker model endpoint to chat-ui and I am getting stuck on the authorization part because I can't pass in request headers to the endpoint. I am able to pass in the authorization string but then I get the following error:

```
Could not parse last message {"message":"Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=AWS4-HMAC-SHA256 Credential=<redacted>, Signature=<redacted>"}
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseGeneratedText (/src/routes/conversation/[id]/+server.ts:196:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async saveMessage (/src/routes/conversation/[id]/+server.ts:107:26)
```

Is it possible to add the ability to pass in headers to the model endpoints in the `.env.local` file?

**Comment by lotif** [comment]
Nevermind, I figured authorization to sagemaker is more complex than I anticipated (as noted by #326 ) and ended up solving the issue differently.

**Comment by julien-c** [comment]
@lotif see #301 btw as sagemaker endpoint support was just merged

**Comment by lotif** [comment]
I saelw that, great news, thanks!!!
