### ISSUE TITLE
Can I add i18n support?

### ISSUE THREAD

**Issue by juancgalvis** [huggingface/chat-ui#372]
Would be great to support the standard i18n in frontend, we can contribute with it, do you see that it would be an accepted contribution?

Maybe using this lib [kaisermann/svelte-i18n](https://github.com/kaisermann/svelte-i18n/blob/main/docs/Getting%20Started.md)

**Comment by nsarrazin** [comment]
I think the models mostly answer in english so I'm not sure i18n is really relevant for us right now.

**Comment by hungryalgo** [comment]
What about support to make chat UI accessible for speakers of other languages? Say Spanish users. To get all the UI displayed in another language, this is not about what the language models output. The app currently hard codes everything in English.

**Comment by marksverdhei** [comment]
> I think the models mostly answer in english so I'm not sure i18n is really relevant for us right now.

Most of the current SOTA open source LLMs answer in different languages depending on the prompt.
I'm currently using this chat UI for self hosted Norwegian language models, and I would love to have support for i18n here.
