### ISSUE TITLE
Clarify if this is/will stay an open source software project

### ISSUE THREAD

**Issue by linux-leo** [huggingface/chat-ui#376]
The [About & Privacy](https://huggingface.co/chat/privacy) page states that:

"The goal of this app is to showcase that it is now (May 2023) possible to build an open source alternative to ChatGPT. 💪"

Due to the text-generation-inference server planning to change their license agreement (https://github.com/huggingface/text-generation-inference/issues/726), HuggingChat needs to either:

1. Keep using [version 0.9.4](https://github.com/huggingface/text-generation-inference/releases/tag/v0.9.4) of the text-generation-inference server (or a fork thereof) and not update to later versions.
2. Change their stated goals as an open source alternative to ChatGPT.

**Comment by julien-c** [comment]
Thanks for your message @linux-leo 

We will work on supporting pluggable backends in chat-ui (there's already a PR open if i remember correctly), and in the meantime this project (and more precisely the docker image in the official Space template) will pin [version 0.9.4](https://github.com/huggingface/text-generation-inference/releases/tag/v0.9.4) of the text-generation-inference server.

Note however that hosting a text-generation-inference endpoint to be used as a backend in chat-ui would not trigger any commercial restriction: a chat interface is not a hosted inference infrastructure product. Similar to if this project was using Elastic as a backend for instance. (and actually this project does use MongoDB)

**Comment by linux-leo** [comment]
Thanks for pinning version 0.9.4 in the Space Template. I was aware that this project wouldn't fall under the commercial restrictions of the new license, I just wanted to know how HuggingChat would respond to this license change. The changes in the official Space Template will be eventually be deployed on [huggingface.co/chat](https://huggingface.co/chat/), right?

**Comment by julien-c** [comment]
we will not change the license of this `chat-ui` repo in the future, it will stay Apache 2.0

Closing this for now but feel free to reopen in the future!
