### ISSUE TITLE
Issue with Text Generation in Stream Mode

### ISSUE THREAD

**Issue by bilal-rachik** [huggingface/chat-ui#380]
Hi

The text generation in stream mode is not functioning as expected on my development server, which is running behind a reverse proxy with the correct base path defined. I'm only receiving a single response in one go, whereas I expect a continuous stream of text.

Please assist me in resolving this issue. Thank you!

**Comment by nsarrazin** [comment]
Mmh this is strange, what kind of endpoint are you using for the inference ?

**Comment by nsarrazin** [comment]
I see that you opened another issue #379, could you show me what your `MODELS` env variable looks like ?

**Comment by bilal-rachik** [comment]
I am facing several issues in the application related to endpoint calls and certain features.

1. Problem with Endpoint Call on Remote Server:

```

ODELS=`[

  {

    "name": "MPT-30b-chat",

    "endpoints": [{"url": https://dmn-ap24182-prod-494cd687.datalab.cloud.echonet/d14201/text-generation-inference/r/notebookSession/64ca5764e01a145ad0ab9280/generate_stream}],

    "description": "A good alternative to ChatGPT",

    "userMessageToken": "<|im_start|>",

    "assistantMessageToken": "<|im_start|>",

    "messageEndToken": "<|im_end|>",

    "preprompt": "A conversation between a user and an LLM-based AI assistant. The assistant gives helpful and honest answers",

    "parameters": {

      "temperature": 0.2,

      "top_p": 0.9,

      "repetition_penalty": 1.2,

      "top_k": 10,

      "truncate": 1000,

      "max_new_tokens": 500

    }

  }

]`

```

When attempting to make an endpoint call on the remote server, I initially encountered a "SELF_SIGNED_CERT_IN_CHAIN" error.

```

6:35:46 PM [vite] ✨ new dependencies optimized: @huggingface/inference

6:35:46 PM [vite] ✨ optimized dependencies changed. reloading

TypeError: fetch failed

    at fetch (/mnt/chat-ui-0.4/node_modules/undici/index.js:109:13)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async eval ([/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10](mailto:/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10))

    at async POST (/src/routes/conversation/[id]/+server.ts:99:16)

    at async Module.render_endpoint ([/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20](mailto:/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20))

    at async resolve ([/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17](mailto:/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17))

    at async Object.handle (/src/hooks.server.ts:66:20)

    at async Module.respond ([/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20](mailto:/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20))

    at async file:///mnt/chat-ui-0.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22 {

  cause: Error: self-signed certificate in certificate chain

      at TLSSocket.onConnectSecure (node:_tls_wrap:1627:34)

      at TLSSocket.emit (node:events:514:28)

      at TLSSocket._finishInit (node:_tls_wrap:1038:8)

      at ssl.onhandshakedone (node:_tls_wrap:824:12) {

    code: 'SELF_SIGNED_CERT_IN_CHAIN'

  }

}

```

I worked around this issue by adding "export NODE_TLS_REJECT_UNAUTHORIZED='0'", but then I faced a "Bad Request" error, and the call never reached the endpoint. It seems to be related to the usage of fetch in Svelte Kit.

```

(node:13878) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

(Use `node --trace-warnings ...` to show where the warning was created)

Could not parse last message <html>

<head><title>400 Bad Request</title></head>

<body>

<center><h1>400 Bad Request</h1></center>

<hr><center>nginx</center>

</body>

</html>

SyntaxError: Unexpected end of JSON input

    at JSON.parse (<anonymous>)

    at parseGeneratedText (/src/routes/conversation/[id]/+server.ts:207:32)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async saveMessage (/src/routes/conversation/[id]/+server.ts:116:26)

```

2.  Problem with Endpoint Call Locally:

```

MODELS=`[

  {

    "name": "MPT-30b-chat",

    "endpoints": [{"url": http://127.0.0.1:8881/generate_stream}],

    "description": "A good alternative to ChatGPT",

    "userMessageToken": "<|im_start|>",

    "assistantMessageToken": "<|im_start|>",

    "messageEndToken": "<|im_end|>",

    "preprompt": "A conversation between a user and an LLM-based AI assistant. The assistant gives helpful and honest answers",

    "parameters": {

      "temperature": 0.2,

      "top_p": 0.9,

      "repetition_penalty": 1.2,

      "top_k": 10,

      "truncate": 1000,

      "max_new_tokens": 500

    }

  }

]`

```

 

Locally, I encountered an "SSL routines" error,

 

```

TypeError: fetch failed

    at fetch (/mnt/chat-ui-0.4/node_modules/undici/index.js:109:13)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async eval ([/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10](mailto:/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10))

    at async POST (/src/routes/conversation/[id]/+server.ts:99:16)

    at async Module.render_endpoint ([/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20](mailto:/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20))

    at async resolve ([/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17](mailto:/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17))

    at async Object.handle (/src/hooks.server.ts:66:20)

   at async Module.respond ([/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20](mailto:/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20))

    at async file:///mnt/chat-ui-0.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22 {

  cause: [Error: C057D813657F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

  ] {

    library: 'SSL routines',

    reason: 'wrong version number',

    code: 'ERR_SSL_WRONG_VERSION_NUMBER'

  }

}

```

 

 

which I resolved by using "http" instead of "https". However, now, although the calls go through, I receive the text as a single block, and the "stream" mode does not function properly. Strangely, today, even when deploying the "llm" model locally, I am not getting any response in the chat. The calls reach the endpoint, and the server responds, but nothing appears on the chat, only "...".

3. Problem with "Delete All Conversation" button:

Another issue I encountered is with the "Delete All Conversation" button. It does not seem to work correctly and does not delete all conversations as expected

```
Fetch event handler is recognized as no-op. No-op fetch handler may bring overhead during navigation. Consider removing the handler if possible.

/chatui/favicon.png:1     Failed to load resource: the server responded with a status of 404 ()

POST https://dmn-ap24182-prod-494cd687.datalab.cloud.echonet/d14201/chat-ui/r/notebookSession/64ca780d22fb0922132d554e/proxy/8889/conversations?/delete 403

```

**Comment by bilal-rachik** [comment]
I have made progress with the endpoint call issue on the remote server by removing the fetch from Svelte Kit in the code:
```
export async function POST({ request, fetch, locals, params }) {
  
}

``` 
Now, the only problems remaining are related to the stream mode not functioning, whether using an endpoint in local or on a remote server, and the "Delete All Conversation" button not working.

I suspect that these issues might be connected to the fact that my development server uses a reverse proxy, causing a miscommunication between the backend and frontend. The only configuration change I made was adding the line:

```
export APP_BASE=/d14201/chat-ui/r/notebookSession/64ca780d22fb0922132d554e/proxy/8889

```

**Comment by bilal-rachik** [comment]
Hello,

I have identified the source of the problem, which lies with the variable {base} in the +page.servers.ts and +page.svelte files. The problematic line is as follows:

"Import {base} from $app/paths;"

After conducting tests, it appears that the value of the "base" variable retrieved in the "page.svelte" files differs from the one retrieved in the "page.server.ts" files.

**Steps**
1. Access the "page.svelte" pages and print the value of "base."
2. Access the "page.server.ts" pages and print the value of "base."

**Expected Results:** The value of "base" should be the same in both files.

**Observed Results:** The values of "base" differ between the "page.svelte" and "page.server.ts" pages.

Can you assist me in resolving this issue?

**Comment by nsarrazin** [comment]
Hi, thanks for digging deeper into this! I'll try to replicate it and come back to you, this should make it easier to come up with a fix.

**Comment by adarshxs** [comment]
I encountered the exact same error.

**Comment by adarshxs** [comment]
Any updates @nsarrazin @bilal-rachik ? I am facing the same error
```
  cause: [Error: C057D813657F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

  ] {

    library: 'SSL routines',

    reason: 'wrong version number',

    code: 'ERR_SSL_WRONG_VERSION_NUMBER'

  }

```

**Comment by adarshxs** [comment]
Yes I got past this issue... Any idea on how to hook up a retrieval system vectordbs of sorts for this?

**Comment by nandhaece07** [comment]
hey @nsarrazin any solution for the issue mentioned, i am also getting the response at once instead of stream mode. can you please assist me to resolve this?

Note that i am using custom endpoint.
