### ISSUE TITLE
Feature request: use template language for prompts 

### ISSUE THREAD

**Issue by AndreasMadsen** [huggingface/chat-ui#382]
I think the current solution of specific prompt properties (`preprompt`, `userMessageToken`, `messageEndToken`, etc.) is too inflexible. I keep running in to edge cases, which are not supported by such this. A more general solution would be to use a simple template language, such as https://handlebarsjs.com.

In particular falcon requires the following format:

```
{{system message}}

User: {{user message 1}}
Falcon: {{assistant message 1}}
User: {{user message 2}}
Falcon:
```

Note that there is no space after the last `Falcon:`. They say this is important for the tokenizer. However, the history does need the space. Such conditional logical is not currently possible.

I don't think the specific template language is important. But in the case of https://handlebarsjs.com, features like HTML escaping and auto indentation should be disabled. ~I would also propose adding a newline "helper": `{{ln}}` for printing a line break.~ This would make byte-accuate formatting possible.

 ## Example:

The input data could be:
```json
{
  "preprompt": "system message",
  "history": [{
    "user": "user message 1",
    "assistant": "assistant message 1"
  }, {
    "user": "user message 1",
    "assistant": null
  }]
}
```

Then different formats could be implemented with:

**Lamma 2:**

```html
{{#each history}}
<s>[INST] {{#if @first}}<<SYS>>{{{@root.preprompt}}}<</SYS>>

{{/if}}{{user}} [/INST]{{#unless @last}}{{assistant}} </s>{{/unless}}
{{/each}}
```

**Falcon:**

```html
{{{preprompt}}}
{{#each history}}
User: {{user}}
Falcon:{{#unless @last}} {{assistant}}{{/unless}}
{{/each}}
```

**Open Assistant:**

```html
{{{preprompt}}}
{{#each history}}
<|prompter|>{{user}}<|endoftext|><|assistant|>{{#unless @last}}{{assistant}}<|endoftext|>{{/unless}}
{{/each}}
```

**Default:**

The current logic could be implemented with: 

```html
{{{preprompt}}}
{{#each history}}
{{@root.userMessageToken}}{{user}}{{@root.userMessageEndToken}}
{{@root.assistantMessageToken}}{{#unless @last}}{{assistant}}{{@root.assistantMessageEndToken}}{{/unless}}
{{/each}}
```

Although, I would suggest not keeping such implementation in the code, but simple mention it in a migration guide.

**Comment by nsarrazin** [comment]
Thanks for bringing this up! I wanted to look at more flexible solutions for prompt formatting and this seems like an elegant solution. Do you want to try implementing it yourself or is this an open issue that anyone could tackle ?

**Comment by AndreasMadsen** [comment]
@nsarrazin I'm not implementing this right now. I might take it up later. If I do, I will say it here.

One concern is the current WebSearch implementation, which has the odd format of using

```
System:
User: 
User: 
User: 
Assistant:
```

as its prompt format. To make that work with a template, I think a separate template for WebSearch would be required. This also raises the question if summary should have its own template too. And if those details should be specified per model or globally.
