### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [huggingface/chat-ui#388]
It doesnt load for me also your website

**Comment by gary149** [comment]
Yes, it's down. Should be back up soon, sorry for the inconvenience.

**Comment by nsarrazin** [comment]
It's back!

**Comment by BenutzerEinsZweiDrei** [comment]
Is the rate limit normal? When i chat at https://huggingface.co/chat/
At the second message it says "too many messages"

**Comment by nsarrazin** [comment]
You should be prompted to login after the second message if you're not logged in. Is that not the case ? If so what browser are you using?

**Comment by BenutzerEinsZweiDrei** [comment]
Thanks yes logging in solved it

**Comment by nsarrazin** [comment]
Thanks for reporting this, I'll have a look, closing this for now since the service is back up 😄
