### ISSUE TITLE
Inject assistant message in the begining of the chat

### ISSUE THREAD

**Issue by matankley** [huggingface/chat-ui#389]
Hey, is it possible to start a conversation with an assistant message showing up as the first message in the chat?

**Comment by nsarrazin** [comment]
Currently not really, what is your use case for this ? We've been thinking about exposing the system prompt and letting users modify it. Would that be enough?

**Comment by matankley** [comment]
I'm developing a chatbot where I want the user to enter the chat ui and see the assistant first message at the beginning of the interaction.

For example imagine a SQL assistant chatbot, I would like to display first message"I'm your sql assistant. How can I help you?"

Does that make sense?

**Comment by gary149** [comment]
Yes, it's really a UX thing that you can add easily by forking chat-ui. For us it doesn't really makes sense to do it.
