### ISSUE TITLE
Request for Email and Password Authentication Option

### ISSUE THREAD

**Issue by bilal-rachik** [huggingface/chat-ui#392]
Hello,

I would like to inquire whether there are plans to implement an authentication method that allows users to create accounts using an email address and password, without relying on OpenID authentication. Currently, I'm facing challenges on my development server, which lacks internet access, rendering OpenID authentication unusable.

Could you please consider adding this authentication feature for users who are in a similar situation?

Thank you in advance for your attention to this request.

**Comment by nsarrazin** [comment]
Hello! 

I think this is an interesting feature idea, I don't think it's on the roadmap for us right now (maybe @gary149 has any thoughts) but we would definitely review any PR for this.

**Comment by gary149** [comment]
Yes feel free to open a PR for it.
