### ISSUE TITLE
Long chat history

### ISSUE THREAD

**Issue by keidev** [huggingface/chat-ui#396]
How do you manage a long chat history?
Do you truncate the history at some point and call the API only with the most recent messages?

**Comment by Dom-Cogan** [comment]
its stored in the mongo database

**Comment by keidev** [comment]
@Dom-Cogan I know that the history is stored in MongoDB, but how does chat-ui handle calls to the Hugging Face API with the conversation history? Is the history truncated to stay within the tokens limit?

**Comment by Dom-Cogan** [comment]
Oh yeah I have no idea. I can't even get it to use my own LLM which is installed on my local machine.

**Comment by nsarrazin** [comment]
The prompt building happens here: https://github.com/huggingface/chat-ui/blob/0ad340edea015777a2c5cb5fe68044ecff53b13f/src/lib/buildPrompt.ts

Basically we try to approximately make it fit in the context window, but text-generation-inference will truncate it anyway.
