### ISSUE TITLE
Chat input not compatible with some languages

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#403]
Basically we use a `handleKeyDown` method that checks if the event is Enter and if so sends the message. (see [here](https://github.com/huggingface/chat-ui/blob/66adc5d11e57c062481f1e72984aacdf34307883/src/lib/components/chat/ChatInput.svelte#L21-L27))

The problem with this approach is that a few alphabets ([japanese](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/217) and [korean](https://github.com/huggingface/chat-ui/issues/358#issuecomment-1643208951) for example)  use autocomplete where you press enter to get the next character. 

A solution could be to replace the `textarea` by an `input type='text'` and wrap it in a form which the browser could then submit (with better i18n) instead of using javascript to detect the `keydown` event.

**Comment by gary149** [comment]
I think this could be fixed without changing the `textarea` (input text is single line).
