### ISSUE TITLE
Deploy Chat UI Spaces Docker template with a PEFT adapter 

### ISSUE THREAD

**Issue by lrtherond** [huggingface/chat-ui#409]
I tried to accomplish this, but the container failed to launch the chat-ui app, as it seems to assume the model would be a non-adapted model.

Is there a way to make it work?

**Comment by lrtherond** [comment]
Well, I figured something out, but now deploying Chat UI Docker instances to Spaces is completely broken:

<img width="822" alt="Screenshot 2023-08-22 at 7 53 18 PM" src="https://github.com/huggingface/chat-ui/assets/1578548/8744506d-3554-477e-b48c-c52bea24ebf1">

**Comment by lrtherond** [comment]
> Hi, thanks for reporting this! Can you check again if the instance is broken ? It should work now.

Thanks, but I changed course and split my implementation between an inference endpoint and a Gradio space. That gives more control in formatting the prompt Llama 2 chat desires.

It's working well.

I do have a baseline problem, though.

My fine-tuning dataset included a collection of questions and answers. Now, during inference, the model often uses expression such as "according to the given text" and "the given text", etc. It doesn't feel natural.

**Comment by nsarrazin** [comment]
Glad to hear you found a solution for your setup. I'm not sure the dataset issue is relevant to chat-ui though so I'll be closing this one.
