### ISSUE TITLE
preprompt not being injected for Llama 2

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/chat-ui#412]
1. When I alter the preprompt for a Llama 2 type model, it appears to have no impact. It's as though the preprompt is not there. Sample config for .env.local:

```
MODELS=`[
{
        "name": "Trelis/Llama-2-7b-chat-hf-function-calling",
        "datasetName": "Trelis/function_calling_extended",
        "description": "function calling Llama-7B-chat",
        "websiteUrl": "https://research.Trelis.com",
        "preprompt": "Respond in French to all questions",
        "userMessageToken": "[INST]",
        "assistantMessageToken": "[/INST]",
        "parameters": {
                "temperature": 0.01,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "top_k": 50,
                "truncate": 1000,
                "max_new_tokens": 1024
        },
        "endpoints": [{
                "url": "http://127.0.0.1:8080"
        }]
}
]`
```

Other notes:
- The same model responds to changes in system message when run in colab.

- Here, with chat-ui, I'm running with a tgi server.

- Llama-chat has weird templating whereby the first system and user have to be wrapped in INST. The best that can be done with the default templating is just to separately wrap the system message and each user input in [INST] and [/INST]. That said, I don't think that deviation should be significant enough to mean that the preprompt is ignored... but maybe it is OR maybe I'm making some other mistake?

**Comment by nsarrazin** [comment]
Hello! Thanks for opening an issue.

Can you try the following definition for your model ?

```
MODELS=`[
{
        "name": "Trelis/Llama-2-7b-chat-hf-function-calling",
        "datasetName": "Trelis/function_calling_extended",
        "description": "function calling Llama-7B-chat",
        "websiteUrl": "https://research.Trelis.com",
        "userMessageToken": "",
        "userMessageEndToken": " [/INST] ",
        "assistantMessageToken": "",
        "assistantMessageEndToken": " </s><s>[INST] ",
        "preprompt": "Respond in French to all questions",
        "chatPromptTemplate" : "<s>[INST] <<SYS>>\n{{preprompt}}\n<</SYS>>\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{/ifAssistant}}{{/each}}",
        "parameters": {
                "temperature": 0.01,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "top_k": 50,
                "truncate": 1000,
                "max_new_tokens": 1024
        },
        "endpoints": [{
                "url": "http://127.0.0.1:8080"
        }]
}
]`
```

Let me know if it works.

**Comment by RonanKMcGovern** [comment]
Thanks @nsarrazin ! That line of thinking helped a lot.

Basically, it seems the preprompt doesn't get inserted (which the ReadMe seems to allude to for when a template is used). So, I just hard coded the system message as follows and now the chat is responsive to the pre-prompt (i.e. the model responds in french):
```
MODELS=`[
{
        "name": "Trelis/Llama-2-7b-chat-hf-function-calling",
        "datasetName": "Trelis/function_calling_extended",
        "description": "function calling Llama-7B-chat",
        "websiteUrl": "https://research.Trelis.com",
        "userMessageToken": "",
        "userMessageEndToken": " [/INST] ",
        "assistantMessageToken": "",
        "assistantMessageEndToken": " </s><s>[INST] ",
        "chatPromptTemplate" : "<s>[INST] <<SYS>>\nRespond in French to all questions\n<</SYS>>\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{>
        "parameters": {
                "temperature": 0.01,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "top_k": 50,
                "truncate": 1000,
                "max_new_tokens": 1024
        },
        "endpoints": [{
                "url": "http://127.0.0.1:8080"
        }]
}
]`
```

Still, my understanding of how the prompting works is incomplete as I am not able to replicate the behaviour I get in a colab notebook (where the fine-tuned model responds and makes function calls):
```
MODELS=`[
{
        "name": "Trelis/Llama-2-7b-chat-hf-function-calling-v2",
        "datasetName": "Trelis/function_calling_extended",
        "description": "function calling Llama-7B-chat",
        "websiteUrl": "https://research.Trelis.com",
        "userMessageToken": "",
        "userMessageEndToken": " [/INST] ",
        "assistantMessageToken": "",
        "assistantMessageEndToken": " </s><s>[INST] ",
        "chatPromptTemplate": "<FUNCTIONS>{\"function\":\"search_bing\",\"description\":\"Search the web for content on Bing. This allows users to search online/the internet/the web for content.\",\"arguments\":[{\"name\":\"query\",\"type\":\"string\",\"description\":\"The search query string\"}]},{\"function\":\"search_arxiv\",\"description\":\"Search for research papers on ArXiv. Make use of AND, OR and NOT operators as appropriate to join terms within the query.\",\"arguments\":[{\"name\":\"query\",\"type\":\"string\",\"description\":\"The search query string\"}]}</FUNCTIONS>[INST]\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{/ifAssistant}}{{/each}}",
        "parameters": {
                "temperature": 0.01,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "top_k": 50,
                "truncate": 1000,
                "max_new_tokens": 1024
        },
        "endpoints": [{
                "url": "http://127.0.0.1:8080"
        }]
}
]`
```

Here, for reference, is what I'm doing in colab (no SYS message):
```
    # Define the roles and markers
    B_FUNC, E_FUNC = "<FUNCTIONS>", "</FUNCTIONS>"
    B_INST, E_INST = "[INST]", "[/INST]"

    prompt = f"{B_FUNC}{functionList.strip()}{E_FUNC}{B_INST} {user_prompt.strip()} {E_INST}\n\n"
```
Note that in colab I use the tokenizer to add in the <s> at the start of each sequence. The model itself produces </s> at the end of the sequence. During decoding, these start and end sequences are then stripped, so I don't explicitly handle these tokens (which are actual tokenizer tokens - as opposed to SYS, INST and FUNCTIONS, which are not in the tokenizer vocab).

I need to read more into the chat-ui code to understand how this works under the hood. Passing in a long string to an env variable isn't ideal either, so probably I should modify the code (outside the .env file) to introduce the function block.

**Comment by TheAGames10** [comment]
I didn't want to start a new issue, it's looking like they have deleted the chatbot website. everytime I try to go to the HuggingChat link, it now gives me a 404 error page no matter what.

![sad day](https://github.com/huggingface/chat-ui/assets/111199398/664a5437-41a2-4901-bd9b-94ef7c1839d5)

**Comment by julien-c** [comment]
should be fixed @TheAGames10 as mentioned on the HF repo:)

**Comment by RonanKMcGovern** [comment]
@nsarrazin , I note from the tagged thread that the codellama issue is being addressed in the next release.

This issue seems to be for (at least) Llama models as well (the preprompt not being injected).

I'm not stuck because I'm putting the pre-prompt inline and that works. Feel free to close this issue if you feel guiding people to do that in the ReadMe is best.

**Comment by gary149** [comment]
Closing for now as it seems fixed.
