### ISSUE TITLE
preprompt is missing in the prompt

### ISSUE THREAD

**Issue by key-hh** [huggingface/chat-ui#414]
Hello.
The preprompt is missing in the prompt, and it seems to be empty unless the user changes the custom system prompt separately.
Can you please confirm whether the preprompt in the model config should be entered as the default value?
If that's correct, the section below seems to be the problem.

- https://github.com/huggingface/chat-ui/blob/7533ab7ef4ae22a8529211d4d093964041b58a1e/src/routes/conversation/%5Bid%5D/%2Bserver.ts#L105

**Comment by nsarrazin** [comment]
Thanks for reporting this! I think I fixed it, you were right, please let me know if it's still an issue :smile:
