### ISSUE TITLE
AI response appears without user message, then both appear after refresh.

### ISSUE THREAD

**Issue by konst-aa** [huggingface/chat-ui#423]
I was experimenting with my own back-end and was wanting to get a feel for the interface. Here is what my code looks like:
```py
import json
import random
from fastapi import FastAPI, Request
from fastapi.responses import Response, StreamingResponse

app = FastAPI()


async def yielder():
    yield "data:" + json.dumps(
        {
            "details": {
                "finish_reason": "length",
                "generated_tokens": 1,
                "seed": None,
            },
            "generated_text": "what is happening",
            "token": {"id": random.randrange(0, 2**32), "logprob": -0.34, "special": False, "text": "it's alive!"},
        },separators=(',', ':')
    ) + "\n\n\n"


@app.post("/generate")
@app.post("/")
async def generate(request: Request):
    reqj = await request.json()
    print(reqj)
    return StreamingResponse(
        yielder(),
        media_type="text/event-stream",
        headers={"Content-Type": "text/event-stream"},
    )
```
Upon sending a message, "hi", I get this:
![image](https://github.com/huggingface/chat-ui/assets/40547702/f3751e35-81a0-4a2d-8e85-2063b3df41c0)  
After refreshing the page, everything is rendered properly:  
![image](https://github.com/huggingface/chat-ui/assets/40547702/b18ce772-b0a4-4959-8d96-346a79aebe6d)

What's going on?  
Here is what I used as a reference, which was recommended to me on the HF Discord: [link](https://github.com/gururise/openai_text_generation_inference_server/blob/main/server.py)  
Thanks in advance.

**Comment by EikeKohl** [comment]
Hey @konst-aa, I encountered a similar issue and I did not fully overview what the expected response format looks like, yet. The `parseGeneratedText` function in `src/routes/conversation/[id]/+server.ts` generally takes care of parsing the event stream. By looking at that, I think your response looks correct...

For me what did the trick was yielding two data streams, like so:

```
data: {"token": {"text": "Some text", "special": false}, "generated_text": null, "details": null}

data: {"token": {"text": "Some text", "special": false}, "generated_text": "Some text", "details": null}

```

**Comment by konst-aa** [comment]
@EikeKohl oh snap, thanks! I'll try your approach tonight.

**Comment by konst-aa** [comment]
@EikeKohl it works!!

**Comment by Extremys** [comment]
Hello, Could you elaborate on the solution? We are talking about two simultaneous data stream or consecutive during the stream? Any snippet to share? I'm having an issue consisting in the chat history just drop when you switch of conversation or refresh the page with a similar custom based endpoint. Thanks for your help :)

**Comment by konst-aa** [comment]
@Extremys I gotchu, something like this should work:
```py
import json
import random
from fastapi import FastAPI, Request
from fastapi.responses import Response, StreamingResponse

app = FastAPI()


async def yielder():
    yield "data:" + json.dumps(
        {
            "details": {
                "finish_reason": "length",
                "generated_tokens": 1,
                "seed": None,
            },
            "generated_text": None,
            "token": {"id": random.randrange(0, 2**32), "logprob": -0.34, "special": False, "text": "what is happening"},
        },separators=(',', ':')
    ) + "\n\n\n"
    yield "data:" + json.dumps(
        {
            "details": {
                "finish_reason": "length",
                "generated_tokens": 1,
                "seed": None,
            },
            "generated_text": "what is happening",
            "token": {"id": random.randrange(0, 2**32), "logprob": -0.34, "special": False, "text": "what is happening"},
        },separators=(',', ':')
    ) + "\n\n\n"


@app.post("/generate")
@app.post("/")
async def generate(request: Request):
    reqj = await request.json()
    print(reqj)
    return StreamingResponse(
        yielder(),
        media_type="text/event-stream",
        headers={"Content-Type": "text/event-stream"},
    )
```

Note: I don't think the `text` field of the token is relevant.
