### ISSUE TITLE
Server does not support event stream content error for custom endpoints

### ISSUE THREAD

**Issue by nandhaece07** [huggingface/chat-ui#430]
is there anyone faced the issue such as "Server does not support event stream content" when parsing the custom endpoint results.
what is the solution for this error?

In order to reproduce the issue,
User enter prompts saying "how are you" -> call goes to custom endpoint -> Endpoint returns response as string -> error popsup "Server does not support event stream content"

**Comment by EikeKohl** [comment]
Hey @nandhaece07 can you please provide more detailed information on how your endpoint's response looks like? And where do you host this endpoint?

To me that sounds like either your response header is missing some information or there is a format issue with your payload. 
Make sure to include the `Content-Type` header in your response and set it to `text/event-stream`.

Here is an example of how your endpoints response payload could look like:

```
data: {"token": {"text": "This is just some dummy text", "special": false}, "generated_text": null, "details": null}

data: {"token": {"text": "Some text", "special": false}, "generated_text": "Some more text", "details": null}

```

You can find more on the format of an event stream response here: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by nandhaece07** [comment]
@EikeKohl thanks for the update. you cleared the doubts i had. thanks much!

**Comment by dillfrescott** [comment]
Same exact issue. Havent been able to solve it. Ive tried many things
