### ISSUE TITLE
Web search code too slow compared to existing alternative running on amateur infra

### ISSUE THREAD

**Issue by sarutobiumon** [huggingface/chat-ui#439]
Please consider integrating the web search code from the UI interface created with the code below:
https://github.com/NimbleBoxAI/ChainFury

**Comment by nsarrazin** [comment]
Hi! We're always open to new contributions, feel free to open a PR for something you think would be worthwhile!

**Comment by julien-c** [comment]
> amateur infra

there's no such thing as amateur infra 🤣
