### ISSUE TITLE
Web Search not working 

### ISSUE THREAD

**Issue by bilalazhar72** [huggingface/chat-ui#440]
i have been having this issues where it just searches something but then never shows me the answer it shows max tokens
i just keep seeing this
first i see the links of the resources

but then it does nothing at all

![image](https://github.com/huggingface/chat-ui/assets/108006611/6eefb6a4-426e-408c-85bb-1106161fd481)

i just see this and do not even get the model response

**Comment by nsarrazin** [comment]
Hi! Thanks for reporting this. Which model are you using ?

**Comment by krampstudio** [comment]
I'm getting it also with falcon

**Comment by bilalazhar72** [comment]
i am getting this with every model on the page , ill do more testing and paste it here for more context

**Comment by nsarrazin** [comment]
This should be fixed with the latest falcon! Can you report back ?

**Comment by nsarrazin** [comment]
Gonna close this, let me know if it's still broken.
