### ISSUE TITLE
Feature request:  render latex

### ISSUE THREAD

**Issue by samsja** [huggingface/chat-ui#446]
# Context

I am using the chat-ui via the huggingface chat platform and planning to use the chat-ui with my own model as well. First thanks for making this tool open source.

One problem that I encounter while using it is that it does not render markdown like chat gpt UI do. (attaching a screenshot to show).

I think that it could be a great feature to be able to render latex inside the UI.

Thanks in advance!

![Screenshot from 2023-09-18 16-23-51](https://github.com/huggingface/chat-ui/assets/55492238/b2c41f6c-934e-4550-8aa3-dd196e78c332)
![Screenshot from 2023-09-18 16-23-41](https://github.com/huggingface/chat-ui/assets/55492238/a6cacc21-0dbe-4e78-b669-177bd6e47d7f)

**Comment by julien-blanchon** [comment]
See here for a working PR: https://github.com/huggingface/chat-ui/pull/450

**Comment by samsja** [comment]
nice this rock :rocket:

**Comment by julien-c** [comment]
feedback is welcome on PR #450! Thanks a lot!!

**Comment by nsarrazin** [comment]
We merged #450, closing this !
