### ISSUE TITLE
Custom chatbot which includes sources such as pdf,databases and  a specific website only.

### ISSUE THREAD

**Issue by pranavbhat12** [huggingface/chat-ui#471]
I have a chatbot which can query pdf,database,a particular website in python.How do I include may be the quantized models,rag sources and the retrieval logic in this chat ui?

**Comment by nsarrazin** [comment]
We don't easily support plugging in your own backend at the moment. Easiest option might be a fork for your use case I think.

**Comment by jackbravo** [comment]
This is being worked on at PR #641
