### ISSUE TITLE
Create git tag for v0.6.0

### ISSUE THREAD

**Issue by michaelfeil** [huggingface/chat-ui#474]
Since https://github.com/huggingface/chat-ui/commit/e5afba2a361e92c696ca0165081a2ce6aaf60a32 there is the `package.json` `v0.6.0` -> Could you also create an according `git tag`?

**Comment by nsarrazin** [comment]
Good catch! thanks

**Comment by nsarrazin** [comment]
It's [fixed](https://github.com/huggingface/chat-ui/releases/tag/v0.6)!
