### ISSUE TITLE
Model selection: Enable scrolling for long model lists 

### ISSUE THREAD

**Issue by michaelfeil** [huggingface/chat-ui#475]
I noticed with more than 3/4 models in the model-selection menu, you need to use the browsers zoom tools (CTRL&+) 
With more than 5 to 6 models, also the `apply` button is hidden on standard zoom.
For example with 

# Issue:
Issue with Regular Zoom: Missing models or hidden "APPLY" button.
![image](https://github.com/huggingface/chat-ui/assets/63565275/d3e6ec52-210e-46ad-87d0-c80639055c5c)

# Fix:

Zoomed out in Chrome/Edge to 80%
![image](https://github.com/huggingface/chat-ui/assets/63565275/36c22403-fffd-4ae3-870c-ba1f1aa2be86)

**Comment by nsarrazin** [comment]
cc @gary149 do we want to fix this or just make it part of the new settings ?

**Comment by gary149** [comment]
I cannot reproduce can you @nsarrazin ?
