### ISSUE TITLE
Make the description customizable in the .env

### ISSUE THREAD

**Issue by sjbpsh** [huggingface/chat-ui#495]
I'd like to customize the description of chat-ui as marked below. But I can't find how to do it in your tutorial, README.md.
It would be highly appreciated if you assist.

![image](https://github.com/huggingface/chat-ui/assets/142883089/046d3926-ddef-4da8-87a7-8771db218976)

**Comment by ViokingTung** [comment]
excuse me, have you used TGI of Llama-2-70b-chat-hf as a backend for chat-ui? does it work?

**Comment by nsarrazin** [comment]
Hi! I don't think it's possible to do it from the .env for now, your best bet would be to modify the code directly indeed. 

Is it a feature you would like to see?

**Comment by julien-c** [comment]
Feel free to open a PR in case you would like that to be configurable through the env. Should be easy!

**Comment by nsarrazin** [comment]
Pointers if someone wants to work on this:

* You could add a new variable in the .env called `PUBLIC_APP_DESCRIPTION` 
* In the [`ChatIntroduction.svelte`](https://github.com/huggingface/chat-ui/blob/d779ad08e090c9c8ab9decdfd6cc7d25031e0274/src/lib/components/chat/ChatIntroduction.svelte#L43) file you can replace the text by `PUBLIC_APP_DESCRIPTION` and defaulting to the same text we have now if it's undefined

**Comment by sjbpsh** [comment]
@julien-blanchon, @nsarrazin, thank you sooooooooo much. I feel like the world has become a little warmer thanks to you.

**Comment by julien-blanchon** [comment]
@nsarrazin @sjbpsh I've implement this in https://github.com/huggingface/chat-ui/pull/507

**Comment by nsarrazin** [comment]
Feature has been merged, closing the issue!
