### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by Bikalpa-Paudel** [huggingface/chat-ui#505]
**Issue Title:** Add Icons to Navbar

**Description:**
I would like to suggest enhancing the user experience of the website by adding icons to the navigation bar. This small but significant improvement can make navigation more intuitive and visually appealing.

![image](https://github.com/huggingface/chat-ui/assets/89839823/87199394-0bb5-4cb6-aebb-49cf334c7409)

**Reasoning:**
- Icons provide visual cues that can help users quickly identify and understand the purpose of each navigation item.

**Comment by Bikalpa-Paudel** [comment]
> **Issue Title:** Add Icons to Navbar
> 
> **Description:** I would like to suggest enhancing the user experience of the website by adding icons to the navigation bar. This small but significant improvement can make navigation more intuitive and visually appealing.
> 
> ![image](https://user-images.githubusercontent.com/89839823/274479900-87199394-0bb5-4cb6-aebb-49cf334c7409.png)
> 
> **Reasoning:**
> 
> * Icons provide visual cues that can help users quickly identify and understand the purpose of each navigation item.

If this idea is accepted, I'm excited to help make it happen

**Comment by nsarrazin** [comment]
We tried it but in the end it didn't get merged (see #272, #247, #143 for full context)

**Comment by Bikalpa-Paudel** [comment]
Thank you for letting me know :)
