### ISSUE TITLE
Feature Request: Option to prevent previous chat history as input.

### ISSUE THREAD

**Issue by calycekr** [huggingface/chat-ui#529]
**Please make a option to prevent previous chat history as input.**
Each query should be independent, without reference to previous context.
Depending on the task, it may not be necessary to use previous context, and it's easy to zero-shot test.

**Comment by nsarrazin** [comment]
Hi! I'm trying to understand the feature request, seems to me like you could create new conversations if you don't want chat history. is that not working out for your use case? 👀

**Comment by gary149** [comment]
> seems to me like you could create new conversations if you don't want chat history

Yes it seems to be the right way to do this 👀
