### ISSUE TITLE
Login issue with Google OpenID

### ISSUE THREAD

**Issue by shagunhexo** [huggingface/chat-ui#534]
I set up google OpenID for my chatUI. I have set the scope to openId and ./auth/userinfo.profile in OAuth Consent Screen. I tried to log the data shared by google to the app and it was the following 

{
  sub: '****',
  picture: 'https://lh3.googleusercontent.com/****',
  email: 'shagun@****',
  email_verified: true,
  hd: '*****'
} 

As you can see, the name is not being shared and hence I am getting an error as Name is a required field. How can I fix this? 

Note: Google shares name for some accounts and for them it does not. This is my first time working with OpenID so any help will be appreciated.

**Comment by nsarrazin** [comment]
Hi, not sure what your .env.local looks like but can you try setting the scopes to `openid profile email` if not already done ?

And can you show me your openid config in the .env.local (and hiding any secrets?)

**Comment by shagunhexo** [comment]
Thanks for prompt reply @nsarrazin 

My .env.local looked like this 

```
OPENID_CONFIG=`{
  "PROVIDER_URL": "https://accounts.google.com",
  "CLIENT_ID": "*****",
  "CLIENT_SECRET": "****",
  "SCOPES": "email"
}`
```

I changed the "SCOPES":"openid profile email" 

Now it works perfectly fine!!

Is there any plan to provide multiple login options? With firebase or something similar?

**Comment by nsarrazin** [comment]
Nice! Happy to hear.

I don't think it's currently on the roadmap but if someone has an implementation that works i'm sure we could merge it 😄 

Closing this issue for now as the problem was fixed but if you want a feature request for firebase for example feel free to open one!
