### ISSUE TITLE
Stream Generation on the UI seems not works well.

### ISSUE THREAD

**Issue by jason9693** [huggingface/chat-ui#547]
**Description:**
Currently, I am facing an issue in my service where tokens enqueued from the server should be used to display data in the UI as a stream, but there seems to be a problem in this process. Below is a detailed explanation of the issue.

**Scenario:**

Tokens are enqueued from the server.
The UI should receive enqueued tokens and display them as a streaming data feed.
However, the streaming functionality in the UI is not working as expected.

**Problem:**

Enqueued tokens are not being displayed in the UI as a stream especially short answer.
The UI server receives tokens but fails to render or update them.

https://github.com/huggingface/chat-ui/assets/11185336/404deb1c-9ca2-43dd-8fea-4d40b47b86ce

**Cause:**

I am currently in the process of debugging to determine the root cause of this issue. The exact cause has not been identified yet.
Reproducible Steps:

1. enqueue the token in `src/routes/conversation/[id]/+server.ts/`
- controller.enqueue(JSON.stringify(newUpdate) + "\n");
2. try dequeue with stream.read() in `src/routes/conversation/[id]/+page.svelte`
- `await reader?.read().then(async ({ done, value }) => {...`

**Expected Behavior:**

Enqueued tokens from the server should be displayed correctly as a streaming feed in the UI.

**Comment by hungryalgo** [comment]
any updates? 

I find token generation in general is an issue, even with default settings, I either get a network error, or no tokens generated. This is deployment with the main branch, with no code changes on my end.

However, if you try:
https://huggingface.co/chat/
That deployment somehow has no issues. 

Many users seem to have similar issues:
https://huggingface.co/spaces/huggingchat/chat-ui/discussions/306
https://huggingface.co/spaces/huggingchat/chat-ui/discussions/300
https://huggingface.co/spaces/huggingchat/chat-ui/discussions/294

**Comment by jason9693** [comment]
It seems 

`await reader?.read().then(async ({ done, value }) => {
`
function in src/routes/conversation/[id]/+page.svelte/writeMessage 
is blocked while they receive 4096 characters from the server stream sent.


<img width="527" alt="스크린샷 2023-11-13 오후 12 47 54" src="https://github.com/huggingface/chat-ui/assets/11185336/3c09d208-adee-4d12-8429-f0cde87b7b8d">

Currently I'm finding to change the stream buffer size.

**Comment by nsarrazin** [comment]
Thanks for bringing this up. I can reproduce a similar issue but only using firefox. Chrome and Safari actually work fine, do you have the same findings ?

**Comment by jason9693** [comment]
@nsarrazin Yes, the picture was tested in chrome.

**Comment by nsarrazin** [comment]
I think we can close this now that #561 is merged, let me know if it's not fixed.
