### ISSUE TITLE
Can this ui be run on a colab?

### ISSUE THREAD

**Issue by amida47** [huggingface/chat-ui#550]
I am wondering if this ui can be used inside a colab.

**Comment by gary149** [comment]
Good question, not a colab expert but I guess not directly as it's using javascript but maybe using a thin python wrapper?

**Comment by nsarrazin** [comment]
It is [technically possible](https://stackoverflow.com/questions/76267556/how-can-i-install-node-14-on-google-collab) to install node directly in google colab I guess but I think this is outside the scope of this repo...
