### ISSUE TITLE
Fully local websearch option

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#553]
The 3 providers we currently support for websearch all require the use of external APIs. For HuggingChat this makes sense since we serve a lot of users. But for local users, it would be beneficial to fetch search results without using an API.

We already parse the DOM of the resulting pages to extract the text, so I think it wouldn't be much more work to offer an option to parse the google results page too to extract the links.

What do you think @mishig25 ?

**Comment by mishig25** [comment]
In this case, what needs to be changed?

**Comment by nsarrazin** [comment]
I think we would need to generate the google url directly, fetch it and extract the result URLs from the google search HTML. See this [plugin](https://github.com/simbake/web_search/blob/main/script.py#L18-L27) for another chat UI which does something similar

**Comment by iChristGit** [comment]
I am following! would love to have this feature so much!

**Comment by mishig25** [comment]
will work on it 👍
