### ISSUE TITLE
trying to replicate the api search with the local search option

### ISSUE THREAD

**Issue by iChristGit** [huggingface/chat-ui#571]
When I try searching for information on the site (huggingface.co/chat) it works fine and gives correct information, but when doing the same thing using the same model  I get hallucinations..
Ive tried all sorts of temperature settings and models.
This is the result locally:
![image](https://github.com/huggingface/chat-ui/assets/20077386/cee5a762-3004-4953-9a9b-c6dc2291c569)
This is with the site:
![image](https://github.com/huggingface/chat-ui/assets/20077386/0f1001bf-6c16-4dc0-84b5-b668d135c1d6)
The sources look the smae on both but the actual response is always not even real information..
This is my current config:

MONGODB_URL=mongodb://localhost:27017
PUBLIC_APP_NAME=PrivateGPT
MODELS=`[
  {
    "name": "text-generation-webui",
    "id": "text-generation-webui",
    "parameters": {
      "temperature": 0.1,
      "top_p": 0.95,
      "repetition_penalty": 1.2,
      "top_k": 12,
      "truncate": 1000,
      "max_new_tokens": 1024,
      "stop": []
    },
    "endpoints": [{
      "type" : "openai",
      "baseURL": "http://127.0.0.1:5000/v1/"
    }]
  }
]`

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1040:13)
    at update (C:/ChatUI/src/routes/conversation/[id]/+server.ts:155:20)
    at Object.start (C:/ChatUI/src/routes/conversation/[id]/+server.ts:189:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_STATE'
}
TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1040:13)
    at update (C:/ChatUI/src/routes/conversation/[id]/+server.ts:155:20)
    at Object.start (C:/ChatUI/src/routes/conversation/[id]/+server.ts:189:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

**Comment by iChristGit** [comment]
What are the settings on the site? so i can try to match the relevant answers?

**Comment by iChristGit** [comment]
Also, does the search supposed to be gathered and indexed and summarized in like 5-10 seconds? it seems too fast maybe something isnt fully working

**Comment by nsarrazin** [comment]
The search is quite fast so I think 5-10 seconds is correct. I'll have to investigate deeper to figure out why your results are different. What model are you using with `text-generation-webui` ?

**Comment by iChristGit** [comment]
> The search is quite fast so I think 5-10 seconds is correct. I'll have to investigate deeper to figure out why your results are different. What model are you using with `text-generation-webui` ?

![Screenshot 2023-11-22 125854](https://github.com/huggingface/chat-ui/assets/20077386/7b927c83-6ab6-49ce-a5b1-9a6110089648)

Ive been trying with all of those models, and with all sort of temperature settings.
Using the example above, I can see the sources are relevant (openai ceo departure etc) but still the answer is 90% of the times about GPT-3 the "new" model instead of the drama it sees in the sources.

If you have better luck than what shown in my example please tell me what settings you use and what model gives you good success!

Thank you

**Comment by nsarrazin** [comment]
![image](https://github.com/huggingface/chat-ui/assets/25119303/06c3fcfb-f17c-4844-afa2-872106e3baf8)
Using zephyr with the llama.cpp server locally I have decent results, not sure what is different about text-generation-webui. I'll look into it

**Comment by iChristGit** [comment]
> ![image](https://user-images.githubusercontent.com/25119303/284885825-06c3fcfb-f17c-4844-afa2-872106e3baf8.png) Using zephyr with the llama.cpp server locally I have decent results, not sure what is different about text-generation-webui. I'll look into it

Il try installing llamacpp and see if the issue is specific to text generation webui.
are those your settings for llamacpp? and can you link the specific model so i can match it ?
        "temperature": 0.1,
        "top_p": 0.95,
        "repetition_penalty": 1.2,
        "top_k": 50,
        "truncate": 1000,
        "max_new_tokens": 2048,

**Comment by iChristGit** [comment]
Have tried to run llama-cpp and cannot connect it to chat-ui:
![image](https://github.com/huggingface/chat-ui/assets/20077386/5bb96c22-d75b-4f6b-886e-202335ac61c0)
Cant seem to run it properly..

**Comment by iChristGit** [comment]
![image](https://github.com/huggingface/chat-ui/assets/20077386/58c5732d-be83-4a73-bf09-561cf02c781c)
Tried text gen webui with llamacpp and zeypher, same results.

**Comment by iChristGit** [comment]
I am trying everything to run llamacpp and it still fails ( I see in console it listening on port8080, copied to example from the tutorial to my local env file

![image](https://github.com/huggingface/chat-ui/assets/20077386/ec3fffdf-78e6-4506-9e86-53a45b0ca182)

**Comment by iChristGit** [comment]
I think this has something to do with the results:
![image](https://github.com/huggingface/chat-ui/assets/20077386/f2223501-5aa6-4d8e-85fa-07f56981df76)
@nsarrazin

**Comment by iChristGit** [comment]
So, i managed to run the llama cpp and indeed the results are solid, the search works, so its something specific to text-gen-webui.

Also, in the readme for cpp it says to format it like:
MODELS=[
  {
It didnt work so I wrote instaed of 
MODELS=`[
  {
That was the whole issue for me with cpp and now it works.

**Comment by AlexBlack2202** [comment]
> > > I think this has something to do with the results as shown in image, but sometimes it query the right term but still gets it all wrong.. im bashing my head trying all sorts of stuff but it wont work ![image](https://private-user-images.githubusercontent.com/20077386/285291938-f2223501-5aa6-4d8e-85fa-07f56981df76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDAyMjgsIm5iZiI6MTcwMTA5OTkyOCwicGF0aCI6Ii8yMDA3NzM4Ni8yODUyOTE5MzgtZjIyMjM1MDEtNWFhNi00ZDhlLTg1ZmEtMDdmNTY5ODFkZjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE1NDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MDBjYzdjNzkxOWJmZTUyYjU3NTFmMzY1YjhkNzdjZTIwNzZhMGY4MGYyZWU4ZGFkNzc0MTcyOTY3MGQwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMX1-NHFOjg_dDzLbY1BHjC9uPEKLKgKqnoPI_gQLIs) @nsarrazin
> > 
> > 
> > how can you enable webSearch, i start it by default and webSearch not appear
> 
> put USE_LOCAL_WEBSEARCH=true in your env.local file, its in the readme.

thank you, it work for me . Can you share me the name of model you use in llama cpp?

**Comment by iChristGit** [comment]
> > > > I think this has something to do with the results as shown in image, but sometimes it query the right term but still gets it all wrong.. im bashing my head trying all sorts of stuff but it wont work ![image](https://private-user-images.githubusercontent.com/20077386/285291938-f2223501-5aa6-4d8e-85fa-07f56981df76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDAyMjgsIm5iZiI6MTcwMTA5OTkyOCwicGF0aCI6Ii8yMDA3NzM4Ni8yODUyOTE5MzgtZjIyMjM1MDEtNWFhNi00ZDhlLTg1ZmEtMDdmNTY5ODFkZjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE1NDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MDBjYzdjNzkxOWJmZTUyYjU3NTFmMzY1YjhkNzdjZTIwNzZhMGY4MGYyZWU4ZGFkNzc0MTcyOTY3MGQwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMX1-NHFOjg_dDzLbY1BHjC9uPEKLKgKqnoPI_gQLIs) @nsarrazin
> > > 
> > > 
> > > how can you enable webSearch, i start it by default and webSearch not appear
> > 
> > 
> > put USE_LOCAL_WEBSEARCH=true in your env.local file, its in the readme.
> 
> thank you, it work for me . Can you share me the name of model you use in llama cpp?

```
MONGODB_URL=mongodb://localhost:27017
USE_LOCAL_WEBSEARCH=true
PUBLIC_APP_ASSETS=chatui
HF_ACCESS_TOKEN=hf_none
PUBLIC_APP_DESCRIPTION="ChatGPT But Open Source!"
PUBLIC_APP_NAME=ChatGPT
MODELS=`[
  {
      "name": "Mythalion-13B",
      "description": "Mythalion is a great overall model",
      "chatPromptTemplate": "{{preprompt}}\nInstruction:{{#each messages}}{{#ifUser}}{{content}}\nResponse:{{/ifUser}}{{#ifAssistant}}{{content}}{{/ifAssistant}}{{/each}}",
       "preprompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.",
       "promptExamples": [
      {
        "title": "Write an email from bullet list",
        "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
      }, {
        "title": "Code a snake game",
        "prompt": "Code a basic snake game in python and give explanations for each step."
      }, {
        "title": "Assist in a task",
        "prompt": "How do I make a delicious lemon cheesecake?"
      }
      ],
      "parameters": {
        "temperature": 0.1,
        "top_p": 0.95,
        "repetition_penalty": 1.2,
        "top_k": 50,
        "truncate": 3072,
        "max_new_tokens": 4096,
        "stop": ["</s>"]
      },
      "endpoints": [{
         "url": "http://127.0.0.1:8080",
         "type": "llamacpp"
        }
      ]
  }
]`
``` 

This is my env.local
And I use mythomax-l2-13b.Q8_0.gguf

**Comment by AlexBlack2202** [comment]
> > > > > I think this has something to do with the results as shown in image, but sometimes it query the right term but still gets it all wrong.. im bashing my head trying all sorts of stuff but it wont work ![image](https://private-user-images.githubusercontent.com/20077386/285291938-f2223501-5aa6-4d8e-85fa-07f56981df76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDAyMjgsIm5iZiI6MTcwMTA5OTkyOCwicGF0aCI6Ii8yMDA3NzM4Ni8yODUyOTE5MzgtZjIyMjM1MDEtNWFhNi00ZDhlLTg1ZmEtMDdmNTY5ODFkZjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE1NDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MDBjYzdjNzkxOWJmZTUyYjU3NTFmMzY1YjhkNzdjZTIwNzZhMGY4MGYyZWU4ZGFkNzc0MTcyOTY3MGQwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMX1-NHFOjg_dDzLbY1BHjC9uPEKLKgKqnoPI_gQLIs) @nsarrazin
> > > > 
> > > > 
> > > > how can you enable webSearch, i start it by default and webSearch not appear
> > > 
> > > 
> > > put USE_LOCAL_WEBSEARCH=true in your env.local file, its in the readme.
> > 
> > 
> > thank you, it work for me . Can you share me the name of model you use in llama cpp?
> 
> ```
> MONGODB_URL=mongodb://localhost:27017
> USE_LOCAL_WEBSEARCH=true
> PUBLIC_APP_ASSETS=chatui
> HF_ACCESS_TOKEN=hf_none
> PUBLIC_APP_DESCRIPTION="ChatGPT But Open Source!"
> PUBLIC_APP_NAME=ChatGPT
> MODELS=`[
>   {
>       "name": "Mythalion-13B",
>       "description": "Mythalion is a great overall model",
>       "chatPromptTemplate": "{{preprompt}}\nInstruction:{{#each messages}}{{#ifUser}}{{content}}\nResponse:{{/ifUser}}{{#ifAssistant}}{{content}}{{/ifAssistant}}{{/each}}",
>        "preprompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.",
>        "promptExamples": [
>       {
>         "title": "Write an email from bullet list",
>         "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
>       }, {
>         "title": "Code a snake game",
>         "prompt": "Code a basic snake game in python and give explanations for each step."
>       }, {
>         "title": "Assist in a task",
>         "prompt": "How do I make a delicious lemon cheesecake?"
>       }
>       ],
>       "parameters": {
>         "temperature": 0.1,
>         "top_p": 0.95,
>         "repetition_penalty": 1.2,
>         "top_k": 50,
>         "truncate": 3072,
>         "max_new_tokens": 4096,
>         "stop": ["</s>"]
>       },
>       "endpoints": [{
>          "url": "http://127.0.0.1:8080",
>          "type": "llamacpp"
>         }
>       ]
>   }
> ]`
> ```
> 
> This is my env.local, its probably not formatted perfectly but works fine. And I use mythomax-l2-13b.Q8_0.gguf, found it very good at search query summarization.

Thank you, it help me alot

**Comment by iChristGit** [comment]
Any leads on this? @nsarrazin

**Comment by aiasophia** [comment]
I get the same with type 'openai'.. Completely ignores search result in response.

**Comment by nsarrazin** [comment]
Seems like an issue with the openai endpoint type. What server do you use with that endpoint @aiasophia is it also `text-generation-webui` ?

Would be good to see if using another server of the same `openai` type works fine, to verifiy if it's an issue with `text-generation-webui` or all `openai` endpoints.

**Comment by aiasophia** [comment]
@nsarrazin Ours is deployed to azure openai, so not run on any local server.

**Comment by nsarrazin** [comment]
Sounds like an issue with the openAI endpoint then. I'll have a look!

**Comment by nsarrazin** [comment]
Indeed we were not passing the search results in the `openai` endpoint type if you used the default `chat_completions` mode. I just merged #608 to fix the issue, so it should now be working.

@aiasophia @iChristGit @AlexBlack2202 can you tell me if this now works for you when using the openai endpoint? It worked for me using `gpt-3.5-turbo` but it'd be good to confirm with other setups :smile:

**Comment by aiasophia** [comment]
@nsarrazin Thank you, it works for us :)

**Comment by iChristGit** [comment]
Yeah It does work! now I can use Text generation webui correctly! thank you
![image](https://github.com/huggingface/chat-ui/assets/20077386/c68bb2e1-1cb5-4c88-be42-727423195dfe)

**Comment by iChristGit** [comment]
> Closing this issue for now, if it doesn't work let me know and I'll reopen it!

A quick question, I am trying to run this model:
https://huggingface.co/TheBloke/dolphin-2_2-yi-34b-GPTQ
As I understand, the Instruction template is set inside the Text-Generation-webui, but the model keeps spitting information, like it cant stop until it gets to max context.
I used the Chat-ML template in the webui, what should i set inside .env.local instead of "stop": [] ?

**Comment by nsarrazin** [comment]
Maybe `"stop":["<|im_end|>"]` ?
