### ISSUE TITLE
chat can't use in my iphone

### ISSUE THREAD

**Issue by fredhu21** [huggingface/chat-ui#572]
Click the "Star chatting" button won't work.

It was supposed to jump to the normal chat page, but it hangs no matter how hard I click the "Star chatting" BUTTON on my mobile device. (iphone/ipad)

It works on PC/Android well

In my humble guess the reason is "3rdparty cookie(chat-ui)", ios won't allow the 3rdparty cookie in mobile browser

![image](https://github.com/huggingface/chat-ui/assets/40168159/ec966789-6234-4097-970e-bc868b6da4c1)

**Comment by fredhu21** [comment]
And it works on Android too...

Just won't work on ios mobile device, say iphone/ipad

**Comment by fredhu21** [comment]
After I enabled the 3rdparty cookie function in my ios devices. It works well now

![image](https://github.com/huggingface/chat-ui/assets/40168159/099b4ae0-2001-4079-9d04-a37c2d778f93)

**Comment by nsarrazin** [comment]
Closing this in favour of #349 !
