### ISSUE TITLE
Preprompt does not get sent to model

### ISSUE THREAD

**Issue by galen-ft** [huggingface/chat-ui#589]
Dear Huggingface team,

Setting the preprompt has no effect on the model. I tested this with the TGI endpoint, but I think it may have an impact on all other endpoints.

It appears that whenever a new conversation is created, an undefined `preprompt` is stored in the DB. (With the exception of the case when a new conversation receives the `preprompt` from an existing conversation.)

Subsequent messages sent to the model in that conversation will all reuse the same empty `preprompt` as preprompts for existing conversations are loaded from their corresponding DB objects. 

This can be traced to the POST request handler in [src/routes/conversation/+server.ts](https://github.com/huggingface/chat-ui/blob/bb33d30b1d97788c7b948748fb2bd60cb53093ba/src/routes/conversation/%2Bserver.ts#L10). 

More specifically, the `preprompt` in the following insert snippet in that [same POST request handler](https://github.com/huggingface/chat-ui/blob/bb33d30b1d97788c7b948748fb2bd60cb53093ba/src/routes/conversation/%2Bserver.ts#L48) evaluates to `undefined`:

```typescript
const res = await collections.conversations.insertOne({
	_id: new ObjectId(),
	title: title || "New Chat",
	messages,
	model: values.model,
	preprompt: preprompt === model?.preprompt ? undefined : preprompt, // <---- preprompt === undefined
	createdAt: new Date(),
	updatedAt: new Date(),
	...(locals.user ? { userId: locals.user._id } : { sessionId: locals.sessionId }),
	...(values.fromShare ? { meta: { fromShareId: values.fromShare } } : {}),
});
```

For example, when the user sends a new message in an existing conversation, the latter is first loaded from the DB on [line 31 in src/routes/conversation/[id]/+server.ts](https://github.com/huggingface/chat-ui/blob/bb33d30b1d97788c7b948748fb2bd60cb53093ba/src/routes/conversation/%5Bid%5D/%2Bserver.ts#L31), and then its corresponding `preprompt` gets sent through to the model endpoint on [line 247 in that same file](https://github.com/huggingface/chat-ui/blob/bb33d30b1d97788c7b948748fb2bd60cb53093ba/src/routes/conversation/%5Bid%5D/%2Bserver.ts#L247).

### Suggested fix

I've created commit [9e62e1cee1](https://github.com/galen-ft/chat-ui/commit/9e62e1cee1519733f18d9ea89c923325c9a6268d) to share the changes that fix the preprompt.

The changes are applied to the POST request handler in [src/routes/conversation/+server.ts](https://github.com/huggingface/chat-ui/blob/bb33d30b1d97788c7b948748fb2bd60cb53093ba/src/routes/conversation/%2Bserver.ts#L48):

```typescript
preprompt = preprompt === undefined ? model?.preprompt : preprompt; // <--- add this line

const res = await collections.conversations.insertOne({
	_id: new ObjectId(),
	title: title || "New Chat",
	messages,
	model: values.model,
	preprompt: preprompt === model?.preprompt ? model?.preprompt : preprompt, // <--- update this line
	createdAt: new Date(),
	updatedAt: new Date(),
	...(locals.user ? { userId: locals.user._id } : { sessionId: locals.sessionId }),
	...(values.fromShare ? { meta: { fromShareId: values.fromShare } } : {}),
});
```

### Similar issues

- https://github.com/huggingface/chat-ui/issues/412
- https://github.com/huggingface/chat-ui/issues/414

**Comment by nsarrazin** [comment]
Closing this issue as the fix was merged. Thanks for your contribution, really appreciate it!
