### ISSUE TITLE
vercel deployment: stream is very choppy

### ISSUE THREAD

**Issue by hungryalgo** [huggingface/chat-ui#590]
When I deploy using vercel, LLM output is displayed and streamed over to UI, the stream is very choppy, and  some of the content gets lost during streaming.

This works locally on my dev machine, but not when I try to deploy it on vercel.

The streaming used to work with vercel deployments, this is the PR that broke it:
https://github.com/huggingface/chat-ui/pull/444

So if i check out a branch before that PR, it would work on vercel.

Any pointers or hints on what I can change to fix this choppy stream issue?

here is an example vercel deployment with the issue:
https://vercel-chat-ui-delta.vercel.app/

here is an example on vercel with code before the [444](https://github.com/huggingface/chat-ui/pull/444) PR that does NOT have the issue, and works fine:
https://areschat.vercel.app/chat/

Thanks!!!

**Comment by mhenrichsen** [comment]
@hungryalgo did you fix it?

**Comment by hungryalgo** [comment]
This issue was fixed. 

May I ask why you are asking? Do you see issues?
