### ISSUE TITLE
TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed

### ISSUE THREAD

**Issue by AlexBlack2202** [huggingface/chat-ui#594]
i use the lasted main version and i have error when make chat, and in GUI , it show "Sorry, something went wrong. Please try again."

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1040:13)
    at update (file:////chat-ui-main/build/server/chunks/_server.ts-38ce6e8d.js:480:22)
    at file:////chat-ui-main/build/server/chunks/_server.ts-38ce6e8d.js:492:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.start (file:////chat-ui-main/build/server/chunks/_server.ts-38ce6e8d.js:585:9) {
  code: 'ERR_INVALID_STATE'

can any one help me to fix this problem

**Comment by nsarrazin** [comment]
Hi, can I see your .env.local (with secrets redacted) please ?

**Comment by AlexBlack2202** [comment]
> Hi, can I see your .env.local (with secrets redacted) please ?

i deploy all on my own server, here is my .env.local 


MODELS=`[
    {
     "name": "Local  evn",
        "websiteUrl": "https://research.Trelis.com",


      "promptExamples": [ ],


 "userMessageToken": "",
        "userMessageEndToken": " [/INST] ",
        "assistantMessageToken": "",
        "assistantMessageEndToken": " </s><s>[INST] ",
   "chatPromptTemplate": "<s>[INST] <<SYS>>\n{{preprompt}}\n<</SYS>>\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{/ifAssistant}}{{/each}}",
      "parameters": {
        "temperature": 0.1,
        "top_p": 0.95,
        "repetition_penalty": 1.2,
        "top_k": 50,
        "truncate": 3072,
        "max_new_tokens": 4096,
        "stop": ["</s>"]
      },
      "endpoints": [
        {
         "url": "http://127.0.0.1:8089",
         "type": "llamacpp"
        }
      ]
    }
]`





MONGODB_URL=mongodb://localhost:27017
MONGODB_DB_NAME=chat-ui
MONGODB_DIRECT_CONNECTION=false

COOKIE_NAME=hf-chat
HF_ACCESS_TOKEN="fgvhay" # from https://huggingface.co/settings/token
HF_API_ROOT=https://api-inference.huggingface.co/models
OPENAI_API_KEY=#your openai api key here

# used to activate search with web functionality. disabled if none are defined. choose one of the following:
YDC_API_KEY=#your docs.you.com api key here
SERPER_API_KEY=#your serper.dev api key here
SERPAPI_KEY=#your serpapi key here
USE_LOCAL_WEBSEARCH= true #set to true to parse google results yourself, overrides other API keys

# Parameters to enable open id login
OPENID_CONFIG=`{
  "PROVIDER_URL": "",
  "CLIENT_ID": "",
  "CLIENT_SECRET": "",
  "SCOPES": ""
}`

# /!\ legacy openid settings, prefer the config above
OPENID_CLIENT_ID=
OPENID_CLIENT_SECRET=
OPENID_SCOPES="openid profile" # Add "email" for some providers like Google that do not provide preferred_username
OPENID_PROVIDER_URL=https://huggingface.co # for Google, use https://accounts.google.com
OPENID_TOLERANCE=
OPENID_RESOURCE=

# Parameters to enable a global mTLS context for client fetch requests
USE_CLIENT_CERTIFICATE=false
CERT_PATH=#
KEY_PATH=#
CA_PATH=#
CLIENT_KEY_PASSWORD=#
REJECT_UNAUTHORIZED=true

OLD_MODELS=`[]`# any removed models, `{ name: string, displayName?: string, id?: string }`
TASK_MODEL='' # name of the model used for tasks such as summarizing title, creating query, etc.

PUBLIC_ORIGIN=#https://huggingface.co
PUBLIC_SHARE_PREFIX=#https://hf.co/chat
PUBLIC_GOOGLE_ANALYTICS_ID=#G-XXXXXXXX / Leave empty to disable
PUBLIC_ANNOUNCEMENT_BANNERS=`[
    {
    "title": "Llama v2 is live on HuggingChat! 🦙",
    "linkTitle": "Announcement",
    "linkHref": "https://huggingface.co/blog/llama2"
  }
]`

PARQUET_EXPORT_DATASET=
PARQUET_EXPORT_HF_TOKEN=
PARQUET_EXPORT_SECRET=

RATE_LIMIT= 16 # requests per minute
MESSAGES_BEFORE_LOGIN= 5 # how many messages a user can send in a conversation before having to login. set to 0 to force login right away

PUBLIC_APP_NAME=ChatUI # name used as title throughout the app
PUBLIC_APP_ASSETS=chatui # used to find logos & favicons in static/$PUBLIC_APP_ASSETS
PUBLIC_APP_COLOR=blue # can be any of tailwind colors: https://tailwindcss.com/docs/customizing-colors#default-color-palette
PUBLIC_APP_DESCRIPTION="Making the community's best AI chat models available to everyone." # description used throughout the app (if not set, a default one will be used)
PUBLIC_APP_DATA_SHARING=0 #set to 1 to enable options & text regarding data sharing
PUBLIC_APP_DISCLAIMER=0 #set to 1 to show a disclaimer on login page
LLM_SUMMERIZATION=true

**Comment by AlexBlack2202** [comment]
> Is it on every message? only with web search?

it on every message

**Comment by iChristGit** [comment]
> > Is it on every message? only with web search?
> 
> it on every message

```
MONGODB_URL=mongodb://localhost:27017
USE_LOCAL_WEBSEARCH=true
PUBLIC_APP_ASSETS=chatui
HF_ACCESS_TOKEN=hf_none
PUBLIC_APP_DESCRIPTION="ChatGPT But Open Source!"
PUBLIC_APP_NAME=ChatGPT
MODELS=`[
  {
      "name": "Mythalion-13B",
      "description": "Mythalion is a great overall model",
      "chatPromptTemplate": "{{preprompt}}\nInstruction:{{#each messages}}{{#ifUser}}{{content}}\nResponse:{{/ifUser}}{{#ifAssistant}}{{content}}{{/ifAssistant}}{{/each}}",
       "preprompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.",
       "promptExamples": [
      {
        "title": "Write an email from bullet list",
        "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
      }, {
        "title": "Code a snake game",
        "prompt": "Code a basic snake game in python and give explanations for each step."
      }, {
        "title": "Assist in a task",
        "prompt": "How do I make a delicious lemon cheesecake?"
      }
      ],
      "parameters": {
        "temperature": 0.1,
        "top_p": 0.95,
        "repetition_penalty": 1.2,
        "top_k": 50,
        "truncate": 8192,
        "max_new_tokens": 4096,
        "stop": ["</s>"]
      },
      "endpoints": [{
         "url": "http://127.0.0.1:8080",
         "type": "llamacpp"
        }
      ]
  }
]`

# server -m D:\TextGen\models\zephyr\llama-2-13b-chat.Q8_0.gguf -c 4096 -n 1 -np 3 --gpu-layers 64
``` 

This is my working setup with llamacpp, try adjusting yours to look simillar, also make sure the prot number is correct and you can see the docs in 127.0.0.1:8080/docs

**Comment by AlexBlack2202** [comment]
> > > Is it on every message? only with web search?
> > 
> > 
> > it on every message
> 
> ```
> MONGODB_URL=mongodb://localhost:27017
> USE_LOCAL_WEBSEARCH=true
> PUBLIC_APP_ASSETS=chatui
> HF_ACCESS_TOKEN=hf_none
> PUBLIC_APP_DESCRIPTION="ChatGPT But Open Source!"
> PUBLIC_APP_NAME=ChatGPT
> MODELS=`[
>   {
>       "name": "Mythalion-13B",
>       "description": "Mythalion is a great overall model",
>       "chatPromptTemplate": "{{preprompt}}\nInstruction:{{#each messages}}{{#ifUser}}{{content}}\nResponse:{{/ifUser}}{{#ifAssistant}}{{content}}{{/ifAssistant}}{{/each}}",
>        "preprompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.",
>        "promptExamples": [
>       {
>         "title": "Write an email from bullet list",
>         "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
>       }, {
>         "title": "Code a snake game",
>         "prompt": "Code a basic snake game in python and give explanations for each step."
>       }, {
>         "title": "Assist in a task",
>         "prompt": "How do I make a delicious lemon cheesecake?"
>       }
>       ],
>       "parameters": {
>         "temperature": 0.1,
>         "top_p": 0.95,
>         "repetition_penalty": 1.2,
>         "top_k": 50,
>         "truncate": 8192,
>         "max_new_tokens": 4096,
>         "stop": ["</s>"]
>       },
>       "endpoints": [{
>          "url": "http://127.0.0.1:8080",
>          "type": "llamacpp"
>         }
>       ]
>   }
> ]`
> 
> # server -m D:\TextGen\models\zephyr\llama-2-13b-chat.Q8_0.gguf -c 4096 -n 1 -np 3 --gpu-layers 64
> ```
> 
> This is my working setup with llamacpp, try adjusting yours to look simillar, also make sure the prot number is correct and you can see the docs in 127.0.0.1:8080/docs

i have no problem with llamacpp, it work ok. i checked it with postman and it return text

i meet some problem with huggingface/chat-ui, when i type message , it show "Sorry, something went wrong. Please try again."

and error log in terminal said TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed

**Comment by ManasInd** [comment]
@AlexBlack2202 How were you able to resolve this issue?

**Comment by simbosen** [comment]
If anyone has a solution to this, would greatly appreciate you sharing it. Been running into the same issue

**Comment by AlexBlack2202** [comment]
> @AlexBlack2202 How were you able to resolve this issue?
@simbosen 
if you use llama.cpp, set  -np 2 ( or whatever number > 1) in ./server parameter

**Comment by ardaakdere** [comment]
I start llama2 with the chat UI from HuggingFace and I get the same error. I don't see a setting to change the number of parallel processes ("np", I guess). Do you have a solution for this?

**Comment by AlexBlack2202** [comment]
> I start llama2 with the chat UI from HuggingFace and I get the same error. I don't see a setting to change the number of parallel processes ("np", I guess). Do you have a solution for this?

can you show me your .env.local and .env

**Comment by ardaakdere** [comment]
Yes, here is my env.local.template file, which I didn't edit or make any change:

```python
# Use .env.local to change these variables
# DO NOT EDIT THIS FILE WITH SENSITIVE DATA

MONGODB_URL=${MONGODB_URL}
MONGODB_DB_NAME=chat-ui
MONGODB_DIRECT_CONNECTION=false


COOKIE_NAME=chat-ui
HF_ACCESS_TOKEN=#hf_<token> from from https://huggingface.co/settings/token

# used to activate search with web functionality. disabled if not defined
SERPAPI_KEY=#your serpapi key here

# Parameters to enable "Sign in with HF"
OPENID_CLIENT_ID=
OPENID_CLIENT_SECRET=
OPENID_SCOPES="openid profile" # Add "email" for some providers like Google that do not provide preferred_username
OPENID_PROVIDER_URL=https://huggingface.co # for Google, use https://accounts.google.com


# 'name', 'userMessageToken', 'assistantMessageToken' are required
MODELS=`[
  {
    "name": "${MODEL_NAME}",
    "chatPromptTemplate": "${MODEL_PROMPT_TEMPLATE}",
    "preprompt": "",
    "promptExamples": [
      {
        "title": "Python Fibonacci",
        "prompt": "How can I write a Python function to generate the nth Fibonacci number?"
      }, {
        "title": "What is a meme?",
        "prompt": "What is a meme, and what's the history behind this word?"
      }, {
        "title": "Regex",
        "prompt": "Create a regex to extract dates from logs"
      }
    ],
    "endpoints": [
      {
        "type": "tgi",
        "url": "http://127.0.0.1:8080"
      }
    ],
    "parameters": ${MODEL_PARAMS}
  }
]`
OLD_MODELS=`[]`# any removed models, `{ name: string, displayName?: string, id?: string }`

PUBLIC_ORIGIN=${SPACE_HOST}
PUBLIC_SHARE_PREFIX=${SPACE_HOST}/r
PUBLIC_GOOGLE_ANALYTICS_ID=#G-XXXXXXXX / Leave empty to disable
PUBLIC_DEPRECATED_GOOGLE_ANALYTICS_ID=#UA-XXXXXXXX-X / Leave empty to disable
PUBLIC_ANNOUNCEMENT_BANNERS=`[
  {
    "title": "Chat UI is now open sourced on GitHub",
    "linkTitle": "GitHub repo",
    "linkHref": "https://github.com/huggingface/chat-ui"
  }
]`

PARQUET_EXPORT_DATASET=
PARQUET_EXPORT_HF_TOKEN=
PARQUET_EXPORT_SECRET=

PUBLIC_APP_NAME=${APP_NAME} # name used as title throughout the app
PUBLIC_APP_ASSETS=chatui # used to find logos & favicons in static/$PUBLIC_APP_ASSETS
PUBLIC_APP_COLOR=${APP_COLOR} # can be any of tailwind colors: https://tailwindcss.com/docs/customizing-colors#default-color-palette
PUBLIC_APP_DATA_SHARING=#set to 1 to enable disclaimers & options about data sharing
PUBLIC_APP_DATA_DISCLAIMER=#set to 1 to enable disclaimers about model outputs
``` 

Env variables:
<img width="859" alt="Screenshot 2023-12-15 at 11 06 28" src="https://github.com/huggingface/chat-ui/assets/54773283/68de1b39-a2db-49e6-b3c6-d941a82f4f2f">

**Comment by AlexBlack2202** [comment]
ah you use text-generation-launcher, i use llama.cpp , i am not use  text-generation-launcher so i can not know its parameter, maybe you change --validation-workers = 10  , or read document carefully

**Comment by ardaakdere** [comment]
Yeah, thanks anyway. I'm checking that resource: https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher

I will try and update here if I find a solution.

**Comment by AlexBlack2202** [comment]
> ```python
> text-generation-launcher
> ```

do you use text-generation-launcher or llama.cpp or any thing else?

**Comment by shahul01** [comment]
@AlexBlack2202 I use mistral 7b, and I get the same error on very first prompt

**Comment by loganlebanoff** [comment]
Here's what fixed it for me https://github.com/huggingface/chat-ui/issues/1169#issuecomment-2173309506
