### ISSUE TITLE
Support running from a path other than `/`

### ISSUE THREAD

**Issue by zacps** [huggingface/chat-ui#605]
Currently, as far as I can tell, there's no ability to configure the app so that it runs at (for example):

`https://my.domain.com/an-arbitrary-path/`

It would be useful it if was possible to configure the application to link to resources on a subpath.

**Comment by nsarrazin** [comment]
I think the parameter you want to set is `APP_BASE` in the .env !

For example for huggingchat we use `APP_BASE="/chat"`

**Comment by AlexBlack2202** [comment]
do you set APP_BASE? can you show your config and use the lasted version in main branch

> That doesn't seem to work, requests still go to `/_app/...` and similar.

**Comment by zacps** [comment]
My bad, I didn't realise a rebuild was required to pick up the new setting (I'm running via the docker container).

**Comment by nsarrazin** [comment]
Good to know this worked! Yeah moving the .env to be dynamic imports is planned but didn't have time for the refacto yet. Closing this one for now!
