### ISSUE TITLE
PUBLIC APP DATA SHARING set to 0, yet still available in the app settings

### ISSUE THREAD

**Issue by mdetournay** [huggingface/chat-ui#622]
Hello team 

I've deployed the latest version of the app today. In the .env, I've set the following variable: 

PUBLIC_APP_DATA_SHARING=0 

yet, it still appears available in my settings when deployed. 

<img width="501" alt="image" src="https://github.com/huggingface/chat-ui/assets/10243779/3c55040e-72aa-41f5-84bc-a37186c73595">

Am I the only one with that bug ? (might be that I incorrectly merged the changes from this public repo). 

Thank you for your help!

**Comment by nsarrazin** [comment]
Hi, that could be the case, we did a rework of the settings menu recently. I'll have a look

**Comment by mdetournay** [comment]
Thanks for having looked into this!
