### ISSUE TITLE
isModelsModalOpen is not defined in ChatIntroduction.svelte probably after recent update ?

### ISSUE THREAD

**Issue by DrShivang** [huggingface/chat-ui#628]
Hi getting this error after updating to the latest version :

Am Running :
{
  'chat-ui': '0.6.0',
  npm: '10.2.4',
  node: '21.3.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '44.0',
  icu: '74.1',
  llhttp: '9.1.3',
  modules: '120',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.27.2',
  unicode: '15.1',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.8.172.17-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}
```

> chat-ui@0.6.0 dev
> vite dev



  VITE v4.3.9  ready in 1206 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
(node:1526125) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
12:13:23 AM [vite-plugin-svelte] /home/user/public_html/chatui3/src/lib/components/chat/ChatIntroduction.svelte:53:7 'isModelsModalOpen' is not defined
12:13:23 AM [vite-plugin-svelte] /home/user/public_html/chatui3/src/lib/components/chat/ChatIntroduction.svelte:54:53 'isModelsModalOpen' is not defined
12:13:23 AM [vite-plugin-svelte] /home/user/public_html/chatui3/src/lib/components/chat/ChatIntroduction.svelte:64:22 'isModelsModalOpen' is not defined
ReferenceError: isModelsModalOpen is not defined
    at /home/user/public_html/chatui3/src/lib/components/chat/ChatIntroduction.svelte:61:8
    at Object.$$render (/home/user/public_html/chatui3/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at eval (/home/user/public_html/chatui3/src/lib/components/chat/ChatMessages.svelte:75:99)
    at Object.$$render (/home/user/public_html/chatui3/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at eval (/home/user/public_html/chatui3/src/lib/components/chat/ChatWindow.svelte:116:102)
    at Object.$$render (/home/user/public_html/chatui3/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at /home/user/public_html/chatui3/src/routes/+page.svelte:57:25
    at Object.$$render (/home/user/public_html/chatui3/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (/home/user/public_html/chatui3/.svelte-kit/generated/root.svelte:50:42)
    at eval (/home/user/public_html/chatui3/src/routes/+layout.svelte:203:39)
```

**Comment by nsarrazin** [comment]
I don't think you're running the latest version as there's no reference to `isModelsModalOpen` in the code anymore :sweat_smile: what is your deployment process, do you use  docker/build from source, etc?

**Comment by DrShivang** [comment]
I copied the main repo, installed npm and ran dev also build it during various trials

**Comment by DrShivang** [comment]
Hi, still facing the same issue, have tried copying the repo main several times and beginning from scratch but getting the same error repeatedly.

To test, fetch this repo main branch, install the npm and run dev, see the logs to have similar logs as shown in the OP

Error 500 is beautifully displayed on the frontend.

Something has changed as it was working fine earlier, The problem began once i updated the repo to fetch the latest changes and it never ran again on my dev variant.

**Comment by nsarrazin** [comment]
I still think there is something wrong with your deployment process, as no one else has reported such an issue and `isModelsModalOpen` does not exist in the code. Could your browser or reverse proxy be caching chunks of the build or something?

And just to be sure did you create a `.env.local` file ? If not you need at a minimum
```
MONGODB_URL=mongodb://localhost:27017
```
in the `.env.local` file for chat-ui to run properly.

**Comment by nsarrazin** [comment]
Just to be sure, I cloned a fresh version of the latest main, created a `.env.local ` with
```
MONGODB_URL=mongodb://localhost:27017
```
and then ran
 ```
npm installl
npm run dev
```

and couldn't reproduce your issue

**Comment by DrShivang** [comment]
Thanks, reverse proxy caching maybe.. am using them all.. let me check those areas, thanks for pointing in the direction.

**Comment by DrShivang** [comment]
Thanks @nsarrazin, it was due to the points you mentioned above relating to the caching chunks of build by the CDN that I was getting such errors.
The issue has been verified and resolved.
