### ISSUE TITLE
Formatting is incorrect when using LiteLLM (Together.ai)

### ISSUE THREAD

**Issue by gururise** [huggingface/chat-ui#649]
I'm using Mixtral-7b-Instruct-v0.1 via [LiteLLM](https://github.com/BerriAI/litellm) to provide a OpenAI compatible API to together.ai where the model is hosted.  

Everything works fine, including streaming; however, the formatting is messed up as shown.  Any ideas why?
![image](https://github.com/huggingface/chat-ui/assets/4380009/6855fad2-288f-403e-9ab8-1f2f409fe5c9)

**Comment by nsarrazin** [comment]
That's strange, the newlines are present but they're part of the response as a string and don't get parsed properly. Do you get the same issue when using a different provider or is it only from LiteLLM?

**Comment by gururise** [comment]
I believe I have narrowed this down to an issue in LiteLLM's integration with TogetherAI.  When using OpenAI has the LLM provider and keeping LiteLLM in the loop, everything works as expected.

I have opened an issue with LiteLLM [here](https://github.com/BerriAI/litellm/issues/1222).
