### ISSUE TITLE
chat-ui do not support TGI http url when deploy publicly

### ISSUE THREAD

**Issue by walkacross** [huggingface/chat-ui#658]
hi @nsarrazin, the chat-ui works well locally
~~~
# .env.local
endpoints: [{"type":"tgi","url":"http://127.0.0.1:8080/generate_stream"}]
~~~

but if deploy it in public, when chat from the external brower, get the 403 error:
~~~
403
You don't have access to this conversation. If someone gave you this link, ask them to use the 'share' feature instead.
~~~

this issue may be related this issue https://github.com/huggingface/chat-ui/issues/364

it seems that: chat-ui only support the https url, but the TGI only support the http url. it has conflicts. how to fix this?

**Comment by ViokingTung** [comment]
it seems like your tgi url has some problem, you must confirm you can visit your tgi, test by curl etc.
