### ISSUE TITLE
Add Multi User support

### ISSUE THREAD

**Issue by S0ly** [huggingface/chat-ui#666]
it could be great to add multi user support, if multiple people want to use the app

**Comment by gururise** [comment]
> it could be great to add multi user support, if multiple people want to use the app

Believe the app already supports this. Multi-user seems to work fine for me.

**Comment by S0ly** [comment]
ho ? it does not notify it anywhere.. I will see thanks !

**Comment by nsarrazin** [comment]
See [here](https://github.com/huggingface/chat-ui#openid-connect) in the docs to enable the login feature
