### ISSUE TITLE
Feature to collapse the side-bar

### ISSUE THREAD

**Issue by swapnilmj** [huggingface/chat-ui#674]
A button to collapse the side-bar would help.

**Comment by nsarrazin** [comment]
Seems like a pretty reasonable request! Maybe @gary149 has thoughts, but to me this seems like a good idea, sometimes you don't want people to see your chat history when sharing a screen :laughing:

**Comment by swapnilmj** [comment]
I can see collapse-able sidebar on the UI now. Thanks.
