### ISSUE TITLE
Disable text streaming if user prefers reduced animation

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#684]
I don't think this should be exposed as a UI setting but we could check the `prefers-reduced-motion` [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) and disable the streaming updates if it's set to true. 

See [this discussion on the hub](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/342)

**Comment by Mobius-code** [comment]
Hi there. I'm the one who posted that message to the forum. Thank you for opening this PR. What programming language/skills do I need to know to help on this? I've been learning programming for about 6 months, so I'm still fairly new. I've finished courses on Python and Javascript, and I'm learning C right now. I know developers are busy and I'd like to help if that's possible. Thanks!
