### ISSUE TITLE
OPENAI_API_KEY not delivered to the API

### ISSUE THREAD

**Issue by iarbel84** [huggingface/chat-ui#705]
I want to add GPT-4 to the models on ChatUI (via a Space). I defined an OPENAI_API_KEY secret in the Space, but I'm getting an OpenAI error 401, API key not provided. I followed the repo README to add the key, but it just doesn't work. Here is the relevant code from `.env.local.template`:
```
# OpenAI key
OPENAI_API_KEY=${OPENAI_API_KEY}

MODELS=`[
  {
    "name": "gpt-4-1106-preview",
    "displayName": "gpt-4-turbo",
    "preprompt": "",
    "endpoints": [
      {
        "type": "openai",
      }
    ],
    "parameters": ${MODEL_PARAMS}
  }
]`
```

I also tried adding authorization to the endpoint details:
```
"endpoints": [
  {
    "type": "openai",
    "authorization": "Bearer ${OPENAI_API_KEY}"
  }
]
```
but got exactly the same error. Any help from someone that successfully added an OpenAI model to ChatUI would be appreciated

**Comment by flexchar** [comment]
You should specify your key inlined, if using `OPENAI_API_KEY` variable, `OPENAI_API_KEY="your-key-here"` or you use `apiKey` option inside the `endpoints` object as such:

```bash
MODELS=`[
  {
    "name": "gpt-4-1106-preview",
    "displayName": "gpt-4-turbo",
    "preprompt": "",
    "endpoints": [
      {
        "type": "openai",
        "apiKey": "your-key-here"
      }
    ],
    "parameters": ${MODEL_PARAMS}
  }
]`
```
