### ISSUE TITLE
JSON.parse

### ISSUE THREAD

**Issue by parthdacoder** [huggingface/chat-ui#716]
Have already looked into solving by using JSON5, it's still not working!

SyntaxError: Unexpected token # in JSON at position 418
    at JSON.parse (<anonymous>)
    at C:\Users\Parth\Desktop\chat-ui-main\src\lib\server\embeddingModels.ts:41:60
    at async instantiateModule (file:///C:/Users/Parth/Desktop/chat-ui-main/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50861:9)

**Comment by nsarrazin** [comment]
hey can you pull latest main and let me know if the latest changes improved things ? @parthdacoder

**Comment by parthdacoder** [comment]
@nsarrazin Hey yes, the issue has been resolved. Thank you!
