### ISSUE TITLE
Does chat-ui support offline deployment? I have downloaded the weights to my local computer.

### ISSUE THREAD

**Issue by majestichou** [huggingface/chat-ui#761]
I have downloaded the weights to my local computer. Due to network issues, I am unable to interact with the huggingface website. Can I do offline deployment based on chat-ui and downloaded weights from huggingface? Do I not need to set HF_TOKEN=<your access token>?Does that mean I don't need to set HF_TOKEN=<your access token> in the .env.local file?

**Comment by nsarrazin** [comment]
I think you could try to look at the options we provide for interfacing with [local endpoints](https://github.com/huggingface/chat-ui?tab=readme-ov-file#running-your-own-models-using-a-custom-endpoint). chat-ui does not run inference directly so you need to use a service to generate your answers (either using an API or by running it locally)

You shouldn't need an `HF_TOKEN` if using chat-ui with a local endpoint.

**Comment by majestichou** [comment]
> I think you could try to look at the options we provide for interfacing with [local endpoints](https://github.com/huggingface/chat-ui?tab=readme-ov-file#running-your-own-models-using-a-custom-endpoint). chat-ui does not run inference directly so you need to use a service to generate your answers (either using an API or by running it locally)
> 
> You shouldn't need an `HF_TOKEN` if using chat-ui with a local endpoint.

thanks a lot!
