### ISSUE TITLE
Where are the image and pdf upload features when running on locally using this repo?

### ISSUE THREAD

**Issue by zubu007** [huggingface/chat-ui#774]
I see there are issues and features being talked about and added for the image upload and parsing PDFs as markdown etc. However, I dont see these features in when I cloned this repo and started chatui using "npm run dev" locally. 
Am I missing something? 

#641 are the features I am talking about.

**Comment by nsarrazin** [comment]
Hi, those features are in pull requests, which means they haven't been merged yet, so when you clone the repo you won't be cloning this code as well.

You can check out the branch on which the PR is based to try out the feature, but know that it's still a WIP and we can't really help out with support until the feature is merged back into main.
