### ISSUE TITLE
Settings Page Freezes

### ISSUE THREAD

**Issue by lordsoffallen** [huggingface/chat-ui#818]
When I go to settings to change model (after I ran a convo with a model), the UI settings page can't be closed. It freezes. Right now I have to keep reloading the page to use it

**Comment by julien-c** [comment]
i think i've seen this too

**Comment by nsarrazin** [comment]
Hi, is this is related to HuggingChat or a local chat-ui setup? @lordsoffallen

**Comment by lordsoffallen** [comment]
It is related to HuggingChat. @nsarrazin
