### ISSUE TITLE
Cannot find assistants UI in the repo

### ISSUE THREAD

**Issue by CakeCrusher** [huggingface/chat-ui#837]
Hi @nsarrazin  I recently cloned the chat-ui and I noticed that the new assistants ui is missing, at the very least from the main branch.
Is the assistants ui in the repo somwhere? 
If not is there any plans on making it open-source?
  If so when?

**Comment by julien-c** [comment]
it's in there:)

**Comment by CakeCrusher** [comment]
Where, main branch?

**Comment by nsarrazin** [comment]
You need to enable it in your `.env.local` ! See [here](https://github.com/huggingface/chat-ui/blob/43714c048d9eebf2cb86e74ef3de2f0f2617d972/.env.template#L241) for the config we use in HuggingChat 😄

**Comment by CakeCrusher** [comment]
Thanks resovled
