### ISSUE TITLE
Gemma hangs and the web page crashes

### ISSUE THREAD

**Issue by FrankLeeeee** [huggingface/chat-ui#861]
Hi, I'd like to experience Google's Gemma model and I found that Hugging Face Chat actually supports it and I can activate this model in settings. However, the page hangs and crashes when I send a prompt. Other models work well.

**Comment by nsarrazin** [comment]
Is this still happening ?

**Comment by FrankLeeeee** [comment]
Hi @nsarrazin , it works well now. Thanks.
