### ISSUE TITLE
Self-hosted assistants not using system prompt

### ISSUE THREAD

**Issue by sixlive** [huggingface/chat-ui#881]
## Description
It looks like after updating beyond https://github.com/huggingface/chat-ui/commit/e6addfc54e52ef039cb4477280da7191d53521a0 my self-hosted instance assistants no longer use their system prompt. 

I'm going to continue to investigate but it would be awesome if someone with much more context than me sorted it out before I figure it out though ;)

**Comment by sixlive** [comment]
I'm pretty sure its https://github.com/huggingface/chat-ui/pull/807, specifically

> I refactored buildPrompt and broke it down into preprocessMessages (inject websearch results and images for 
>
> multimodal) and buildPrompt (turn an array of messages into a string prompt).
> 
> I moved the prompt building out of the inference-specific code and into the POST endpoint for new messages. (less code duplication)

**Comment by nsarrazin** [comment]
Taking a look at this now, can you tell me which endpoint type you're using ?

**Comment by sixlive** [comment]
@nsarrazin Heres a screenshop of all the requests made when sending a chat to an assistant that contains a custom prompt.

![CleanShot 2024-02-29 at 11 17 07](https://github.com/huggingface/chat-ui/assets/5108034/3ea2a820-226f-4de3-93ca-c36e030ba216)

and when creating the assistant

![CleanShot 2024-02-29 at 11 19 07](https://github.com/huggingface/chat-ui/assets/5108034/d2095992-d7f6-4d6a-aa12-432ebf8b32b9)

Heres one from just using gpt-3.5-turbo with a custom system prompt (this works as expected)

![CleanShot 2024-02-29 at 11 19 07](https://github.com/huggingface/chat-ui/assets/5108034/37e27efd-54a1-408a-9432-fe664a0d8acf)

**Comment by sixlive** [comment]
Just wanted to bump this, eager to use the new features!

**Comment by nsarrazin** [comment]
I pushed a fix that should have fixed the issue! let me know if it's resolved for you, otherwise I can reopen the issue 😁
