### ISSUE TITLE
Running the project with `npm run dev`, but it does not hot reload.

### ISSUE THREAD

**Issue by CakeCrusher** [huggingface/chat-ui#904]
Am I alone in this issue or are you just developing without hot reload? Does anyone have any ideas on how to resolve it?

**UPDATES:**
It has to do whenever you're running it on WSL.

I guess this is an unrelated issue so feel free to close, but would still be nice to know how to resolve this.

**Comment by CakeCrusher** [comment]
Here is something. I haven't tried it yet. https://vitejs.dev/guide/api-hmr

**Comment by nsarrazin** [comment]
Hi! I'll close this because it's not a chat-ui issue specifically
