### ISSUE TITLE
Feature request: support Cloudflare worker AI backend

### ISSUE THREAD

**Issue by lihan** [huggingface/chat-ui#907]
Currently, chat-uilacks support for integrating Cloudflare Worker AI Backend. As Cloudflare Worker AI provides powerful edge serverless GPU capabilities, integrating it would make AI models more accessible.

**Additional Information:**

https://developers.cloudflare.com/workers-ai/

Thank you!

**Comment by julien-c** [comment]
would be neat!

**Comment by nsarrazin** [comment]
With the release of [`Deploy on cloudflare workers AI`](https://huggingface.co/blog/cloudflare-workers-ai) i'd be super interested to see those endpoint types supported in chat-ui.

Let me know if someone wants to work on this 🚀
