### ISSUE TITLE
Several assistants are broken 

### ISSUE THREAD

**Issue by tin2tin** [huggingface/chat-ui#910]
...due to updates today: 6-3-2024 
Ex. https://hf.co/chat/assistant/65c80b2288d76ebc0fc357ca and https://hf.co/chat/assistant/65e74ce37f362ae0160466b3

![image](https://github.com/huggingface/chat-ui/assets/1322593/7c99c53e-1024-4d40-9fa3-f93a88ae0f3d)

![image](https://github.com/huggingface/chat-ui/assets/1322593/02988f8d-9575-400f-a78b-8c99f9c32503)

**Comment by nsarrazin** [comment]
We had an endpoint outage, I think it should work again, can you try ?

**Comment by tin2tin** [comment]
Seems to bo working again. Thank you!

**Comment by tin2tin** [comment]
Now the same errors are showing again.

**Comment by nsarrazin** [comment]
Hi, should be good btw!

For issues related to availability of HuggingChat models, I'd recommend posting on [the discussion page on the hub](https://huggingface.co/spaces/huggingchat/chat-ui/discussions) in the future :grin:

**Comment by tin2tin** [comment]
I did, but it doesn't seem to be the right place for bugs - there was no reply: https://huggingface.co/spaces/huggingchat/chat-ui/discussions/357#65e8700c79a973413ab8c0bd
