### ISSUE TITLE
Add OpenAI embedding endpoint

### ISSUE THREAD

**Issue by Martok88** [huggingface/chat-ui#911]
I haven't been able to find an on-demand public TEI endpoint, so it would be great to have OpenAI embedding compatibility.

**Comment by nsarrazin** [comment]
I think that makes sense! I tagged this as good first issue.

You can add it under `src/lib/server/embeddingEndpoints`, make a new `openai` folder there. Then take a look at TEI and transformersjs embeddings to see some examples.

Make sure to add your new embedding endpoint in `src/lib/server/embeddingEndpoints/embeddingEndpoints.ts` when you're done! 

If no on else tackles it I'll do it when I have some bandwidth, but this shouldn't be too hard 😄

**Comment by Martok88** [comment]
https://github.com/huggingface/chat-ui/pull/915
