### ISSUE TITLE
Why the chat template of google/gemma-7b-it is invalid josn format in .env.local?

### ISSUE THREAD

**Issue by houghtonweihu** [huggingface/chat-ui#933]
I used the chat template from google/gemma-7b-it in .env.local, shown below:

"chat_template": "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + message['content'] | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}",

I got this error:
 [vite] Error when evaluating SSR module /src/lib/server/models.ts:
|- SyntaxError: Unexpected token ''', "'[" is not valid JSON

**Comment by nsarrazin** [comment]
You're using a jinja template but it should be a handlebars template. If you need help with making your own handlebars, feel free to continue the conversation on your other issue (#934) will be closing this one in the meantime 😄
