### ISSUE TITLE
After deleting all your conversations, all buttons become unusable and the page needs to be refreshed to return to normal.

### ISSUE THREAD

**Issue by mikuh** [huggingface/chat-ui#937]
<img width="392" alt="image" src="https://github.com/huggingface/chat-ui/assets/16199680/e2fc1ffa-4010-4529-97a4-a721b98745aa">

after check this button, go to the new page, no operations can be performed.

**Comment by nsarrazin** [comment]
Can reproduce when testing locally, marked as bug

**Comment by ngegner** [comment]
I am also experiencing this issue, would love to know if there are any updates/workarounds!

**Comment by eclipse-kim** [comment]
I am also experiencing this issue. Please let me know about patch plan.

**Comment by julien-c** [comment]
anyone from the community wants to try and open a PR to fix this?
